                                                  ┌───┐
                                                  │   │
                        ───────────────────────   └───┘
 
───────────────────────────────────┬───────────────────
Adresse                            │ Telefon
───────────────────────────────────┼───────────────────
                                   │   
Firma A.C.O.                       │
Computer Systeme GmbH              │
Pfingstrosenstraße 29              │
D - 8000 München 70                │ 089/714 09 05-08
                                   │   
Firma a.h.c. managementberatungs g │
austrian hotelconsult              │
Schloß Rif                         │
A - 5400 Hallein                   │ 06245/55 46-0
                                   │   
Firma A.P.S.                       │
Automatic Portfolio Systems        │
Rintheimerstraße 11                │
D - 7500 Karlsruhe 1               │ 0721/69 18 17
                                   │   
Firma AB Computergesellschaft m.b. │
Wiedner Hauptstraße 135            │
A - 1050 Wien                      │ 0222/55 16 30, 55 
                                   │   
Firma abacomp-software             │
Busdorfmauer 10                    │
D - 4790 Paderborn                 │ 05251/2 78 99
                                   │   
Firma abacus computer gmbH         │
Weilimdorfer Straße 47             │
D - 7015 Korntal-Münchingen 1      │ 0771/83 10 03
                                   │   
───────────────────────────────────┴───────────────────
