                                                  ÔöîÔöÇÔöÇÔöÇÔöÉ
                                                  Ôöé   Ôöé
                        ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ   ÔööÔöÇÔöÇÔöÇÔöÿ
 
ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔö¼ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ
Adresse                            Ôöé Telefon
ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔö╝ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ
                                   Ôöé   
Firma 2i Industrial Informatics Gm Ôöé
Haierweg 20 e                      Ôöé
D - 7800 Freiburg i.Br.            Ôöé 0761/4 22 57
                                   Ôöé   
Firma A-Consult EDV-Beratungs-GmbH Ôöé
K├ñrntnerstra├ƒe 1                   Ôöé
A - 1010 Wien                      Ôöé 0222/513 32 33, 51
                                   Ôöé   
Firma A.C.O.                       Ôöé
Computer Systeme GmbH              Ôöé
Pfingstrosenstra├ƒe 29              Ôöé
D - 8000 M├╝nchen 70                Ôöé 089/714 09 05-08
                                   Ôöé   
Firma a.h.c. managementberatungs g Ôöé
austrian hotelconsult              Ôöé
Schlo├ƒ Rif                         Ôöé
A - 5400 Hallein                   Ôöé 06245/55 46-0
                                   Ôöé   
Firma A.P.S.                       Ôöé
Automatic Portfolio Systems        Ôöé
Rintheimerstra├ƒe 11                Ôöé
D - 7500 Karlsruhe 1               Ôöé 0721/69 18 17
                                   Ôöé   
Firma AB Computergesellschaft m.b. Ôöé
Wiedner Hauptstra├ƒe 135            Ôöé
A - 1050 Wien                      Ôöé 0222/55 16 30, 55 
                                   Ôöé   
Firma abacomp-software             Ôöé
Busdorfmauer 10                    Ôöé
D - 4790 Paderborn                 Ôöé 05251/2 78 99
                                   Ôöé   
Firma abacus computer gmbH         Ôöé
Weilimdorfer Stra├ƒe 47             Ôöé
D - 7015 Korntal-M├╝nchingen 1      Ôöé 0771/83 10 03
                                   Ôöé   
Firma Abacus Software GmbH         Ôöé
Berggasse 17, Stg. 2               Ôöé
A - 1170 Wien                      Ôöé 0222/31 25 36-0
                                   Ôöé   
ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔö┤ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ
