┌┘ADRESS-LISTE LIEFERANTEN                            Datum: 04.09.90 - SEITE 0001└┐
│┌────────────────────────────────────────────────────────────────────────────────┐│
└┤Mandant (01) ...euroSOFT-WARE - 8010 Graz                        Teilnehmer: 002├┘
 └────────────────────────────────────────────────────────────────────────────────┘
Kunden-Kurzbezeichnung         Kunden-Nummer
Name                           Straße
Zusatz                         Land - PLZ/Ort                 Telefon
────────────────────────────────────────────────────────────────────────────────────
 
Aero-Foto GmbH - 8650 Kapfenbe 001-5002
Aero-Foto Ges.m.b.H.           Schmidgasse 5
                               A   - 8605 Kapfenberg          03862/25-3-6
 
Aero Sanitäranl. - 8010 Graz   001-5003
Aero-Sanitäranlagenbau         Münzgrabenstraße 32
Gesellschaft m.b.H.            A   - 8010 Graz                0316/71-1-11
 
Agnello Tindaro - 8020 Graz    001-5004
Tindaro Agnello                Josef Huber Gasse 35
                               A   - 8020 Graz                0316/91-30-5
 
Agra Grabner GmbH - 8280 Fürst 001-5005
AGRA Grabner Ges.m.b.H.        Hauptplatz 8
                               A   - 8280 Fürstenfeld         03382/22-52
 
Agraunion Südost - 8330 Feldba 001-5006
AGRAUNION SÜDOST               Lugitschstraße 1
reg. Genossenhaft m.b.H.       A   - 8330 Feldbach            03152/22-47
 
Agrosserta - 8042 Graz-Raaba   001-5007
Agraverwertungsv. GenmbH       Dr. Auer Straße 22
Agrosserta                     A   - 8042 Graz-Raaba          0316/40-15-6
 
Akad. Druck u.Verlag - 8010 Gr 001-5010
Akad. Druck u.Verlagsanstalt   Neufeldweg 75
Dr. Struzl                     A   - 8010 Graz                0316/41 1 53
 
Alba-Schuhe - 8141 Unterpremst 001-5011
Alba-Schuhfabrik               Jochen-Rindt-Weg 1
Alois Bauer KG.                A   - 8141 Unterpremstätten    03136/25-36
 
Albogel-Werke GmbH - 8010 Graz 001-5012
Albogel-Werke                  Roseggerkai 3/I
Brandner Ges.m.b.H.            A   - 8010 Graz                0316/73 2 21
 
All-Ha Bau-GmbH - 8041 Graz    001-5013
ALL - HA Baugesellschaft m.b   Herbert-Böckl-Gasse 10
                               A   - 8041 Graz                0316/42 5 92

┌──────────────────────────────────────────────────────────────────────────────────┐
└┐Nutzungsberechtigung: euroSOFT Graz                            (c) 1990 euroSOFT┌┘
