┌┘LISTE FREMDWÄHRUNG                                  Datum: 05.09.90 - SEITE 0001└┐
│┌────────────────────────────────────────────────────────────────────────────────┐│
└┤Mandant (01) ...euroSOFT-WARE - 8010 Graz                        Teilnehmer: 002├┘
 └────────────────────────────────────────────────────────────────────────────────┘
 
                                       Bez.  Einheit   Kurs
                  ────────────────────────────────────────────
                  Fremdwährung 1 :     ÖS            =   0,000

                  Fremdwährung 2 :     DM    1       =   7,000

                  Fremdwährung 3 :     Lire  100     =   1,000

                  Fremdwährung 4 :                   =   0,000

                  Fremdwährung 5 :                   =   0,000

                  Fremdwährung 6 :                   =   0,000

                  Fremdwährung 7 :                   =   0,000

                  Fremdwährung 8 :                   =   0,000

                  Fremdwährung 9 :                   =   0,000

                  Fremdwährung 10:                   =   0,000
 

┌──────────────────────────────────────────────────────────────────────────────────┐
└┐Nutzungsberechtigung: euroSOFT Graz                            (c) 1990 euroSOFT┌┘
