&TITEL       = "ST  DRUCK Fremdwährung"

&FORMULAR    = 10
&FOOT_H      = 2

&DATEI (0) = MASK, SYP_01     >>Fremdwährung
&DATEI (1) = MASK, ST4110     >>Dummy Druckdatei


&KOPF (0)
^┌┘LISTE FREMDWÄHRUNG                                  Datum: @@@@@@@@ - SEITE øøøø└┐ ~NO ~1._DATUM_AKT ~1._SEITE
│┌────────────────────────────────────────────────────────────────────────────────┐│
└┤Mandant (øø) @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                      Teilnehmer: øøø├┘ ~1._NR_MAND ~1._MANDANT ~1._TEILN
 └────────────────────────────────────────────────────────────────────────────────┘
&END


&RUMPF (0)

                                       Bez.  Einheit   Kurs
                  ────────────────────────────────────────────
                  Fremdwährung 1 :     @@@@  @@@@@@@ = ##ø,øøø      ~0.FRWÄ_BE_00 ~0°FRWÄ_EH_00 ~0.FRWÄ_KU_00

                  Fremdwährung 2 :     @@@@  @@@@@@@ = ##ø,øøø      ~0.FRWÄ_BE_01 ~0°FRWÄ_EH_01 ~0.FRWÄ_KU_01

                  Fremdwährung 3 :     @@@@  @@@@@@@ = ##ø,øøø      ~0.FRWÄ_BE_02 ~0°FRWÄ_EH_02 ~0.FRWÄ_KU_02

                  Fremdwährung 4 :     @@@@  @@@@@@@ = ##ø,øøø      ~0.FRWÄ_BE_03 ~0°FRWÄ_EH_03 ~0.FRWÄ_KU_03

                  Fremdwährung 5 :     @@@@  @@@@@@@ = ##ø,øøø      ~0.FRWÄ_BE_04 ~0°FRWÄ_EH_04 ~0.FRWÄ_KU_04

                  Fremdwährung 6 :     @@@@  @@@@@@@ = ##ø,øøø      ~0.FRWÄ_BE_05 ~0°FRWÄ_EH_05 ~0.FRWÄ_KU_05

                  Fremdwährung 7 :     @@@@  @@@@@@@ = ##ø,øøø      ~0.FRWÄ_BE_06 ~0°FRWÄ_EH_06 ~0.FRWÄ_KU_06

                  Fremdwährung 8 :     @@@@  @@@@@@@ = ##ø,øøø      ~0.FRWÄ_BE_07 ~0°FRWÄ_EH_07 ~0.FRWÄ_KU_07

                  Fremdwährung 9 :     @@@@  @@@@@@@ = ##ø,øøø      ~0.FRWÄ_BE_08 ~0°FRWÄ_EH_08 ~0.FRWÄ_KU_08

                  Fremdwährung 10:     @@@@  @@@@@@@ = ##ø,øøø      ~0.FRWÄ_BE_09 ~0°FRWÄ_EH_09 ~0.FRWÄ_KU_09
 
  
&END


&FUSS (0)
┌──────────────────────────────────────────────────────────────────────────────────┐
└┐Nutzungsberechtigung: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@      @@@@@@@@@@@@@@@@@┌┘ ~1._NUTZUNG  ~1._COPYRIGHT
&END

