&TITEL       = "ST  DRUCK Mengen-Einheiten"

&FORMULAR    = 10
&LF_N_ZEILEN = 3
&FOOT_H      = 2

&DATEI (0) = MASK, ST1400
&DATEI (1) = MASK, ST4130


&KOPF (0)
^┌┘LISTE MENGEN-EINHEITEN                              Datum: @@@@@@@@ - SEITE øøøø└┐ ~NO ~1._DATUM_AKT ~1._SEITE
│┌────────────────────────────────────────────────────────────────────────────────┐│
└┤Mandant (øø) @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                      Teilnehmer: øøø├┘ ~1._NR_MAND ~1._MANDANT ~1._TEILN
 └────────────────────────────────────────────────────────────────────────────────┘
 
Match-Code                                 Bezeichnung   Basis-EH Umrechnungs-Faktor
────────────────────────────────────────────────────────────────────────────────────
 
&END

&RUMPF (0)
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    @@@@@@@@@@     @@@@     ###.###.##ø,øøøø \
~0.MG_MATCH                                 ~0.MG_BEZ   ~0°BASIS_EH ~0.UM_RECH
&END


&FUSS (0)
┌──────────────────────────────────────────────────────────────────────────────────┐
└┐Nutzungsberechtigung: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@      @@@@@@@@@@@@@@@@@┌┘ ~1._NUTZUNG  ~1._COPYRIGHT
&END


