&FORMULAR = 10
&LIRAND = 0
&REM SCHACHT = 1
&REM ---
&REM FKO
&REM VA1
&REM END
&REM ---
&REM FRU
&REM VA2
&REM END
&REM ---
&REM Seitenfuss mit Zahlungskonditionen und 4 Zeilen Werbetext
&REM FFU
&REM END
&REM ---
&DATEI (0) = EURODATA, ST1103
&REM ---
!R!FONT12;EXIT;
&REM !R!FONT15;EXIT;
   ──────┤  computer team graz  ├──────
   P. Mayer, Krenngasse 19, 8010 Graz (0316/81-37-61)
──────────────────────────

                                       @@@@@@@@@@@@@@@@@@@@@@@    ~0.TEXT_1




       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                   ~0.ANREDE
       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                   ~0.NAME
       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                   ~0.ZUSATZ

       @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                   ~0.STRASSE
       @@ - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              ~0.LAND ~0.PLZ_ORT
