&TITEL     = "ST  DRUCK Mahnungen Kunden"
&FORMULAR  = 30

&DATEI (0) = MASK, ST1100
&DATEI (1) = MASK, ST4110
&DATEI (2) = MASK, SYP_01
&DATEI (3) = MASK, SYPARA

&KOPF (0)
^!R!FONT52;EXIT;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~BE ~3.KOPFTEXT_0
^@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~2E ~3.KOPFTEXT_1
^@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~2E ~3.KOPFTEXT_2
^@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~2E ~3.KOPFTEXT_3
^@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~2E ~3.KOPFTEXT_4
^@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~2E ~3.KOPFTEXT_5
^@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~2E ~3.KOPFTEXT_6
^@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~2E ~3.KOPFTEXT_7
^@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~2E ~3.KOPFTEXT_8
^Abs.: euroSOFT-WARE P.Mayer, A-8082 Kirchbach 126 ~3E
^───────────────────────────────────────────────── ~3E


@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                                    ~0.ANREDE
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@            ┌────────────┬──────────┬───────┐       ~0.NAME
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@            │ Kunden-Nr. │    Datum │ Seite │       ~0.ZUSATZ
                                               │ ´´´´´´´´´´ │  6.08.92 │ 00001 │       ~0.KUNDE
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@            └────────────┴──────────┴───────┘       ~0.STRASSE
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                            ~0.PLZ_ORT
      
       
                                                ^MAHNUNG  ^                 ^           ~BE ~OP ~NO
       
────────────────────────────────────────────────────────────────────────────────
Beleg-     Beleg-     Fällig    Zins
Datum      Nummer     am        Tage     Rechnung     Zahlung   Restbetrag    MK
────────────────────────────────────────────────────────────────────────────────
 
&END

&RUMPF (0)
 2.07.92   AR/166      6.07.92    30    18.396,00        0,00    18.396,00    1
 
 
 
 
 
 
 
 
                                       Zwischensumme             18.396,00
 
                                       Verzugszinsen 14,00 %        214,60
                                       Mahngebühr                    50,00
 
                                       Gesamtsumme               18.660,60
 
 





             Sehr geehrter Herr Ing. Stöller!

             Sicher haben Sie übersehen, daß die oben angeführte
             Rechnung zur Zahlung fällig geworden ist. Ich bitte
             Sie daher um Überweisung des fälligen Betrages auf
             mein Konto RAIKA Kirchbach, BLZ:38170, Kto:9.332.
     
             Mit freundlichen Grüßen
&END

&FUSS (0)
 
────────────────────────────────────────────────────────────────────────────────
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~2.WERB_TXT_1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~2.WERB_TXT_2
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~2.WERB_TXT_3
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~2.WERB_TXT_4
 
^Gelieferte Ware bleibt bis zur Bezahlung unserer gesamten,  auch aus anderen Lieferungen resultierenden Forderungen,  unser  Eigen-   ~4E
^tum.  Unsere  Verkaufs-  und  Zahlungsbedingungen  gelten als anerkannt, wenn innerhalb von 8 Tagen mittels eingeschriebenen Brief    ~4E
^kein Einwand erhoben wird.  Bei Softwarelieferungen und Dienstleistungen beschränkt sich jeder Garantieanspruch auf den Ersatz von    ~4E
^Disketten! Für Software wird eine Benützungs-Lizenz vergeben, die Programme bleiben in unserem Eigentum. Gerichtsstand ist Graz.     ~4E
&END



>>             leider konnten wir nach unserer ersten Mahnung bis heute noch
>>             keinen Zahlungseingang der fälligen Rechnung feststellen.
>>             Wir bitten Sie deshalb nochmals um sofortigen Ausgleich.
>>             Mit freundlichen Grüßen
>>
>>@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@            │ ´´´´´´´´´´ │ ##.##.## │ ##### │       ~0.ZU_HANDEN ~0.KUNDEN_NUM ~0.DATUMDRUCK ~1._SEITE
>>@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                                 ~1._FREI_1 == LAND+PLZ+ORT
>>!R!FONT52;EXIT;
>>!R!FONT52;EXIT;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~3.KOPFTEXT_0
>>!R!FONT53;EXIT;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~3.KOPFTEXT_1
>>!R!FONT53;EXIT;  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~3.KOPFTEXT_2
>>!R!FONT53;EXIT;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~3.KOPFTEXT_3
>>!R!FONT53;EXIT;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~3.KOPFTEXT_4
>>!R!FONT53;EXIT;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~3.KOPFTEXT_5
>>!R!FONT53;EXIT;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~3.KOPFTEXT_6
>>!R!FONT53;EXIT;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~3.KOPFTEXT_7
>>!R!FONT53;EXIT;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  ~3.KOPFTEXT_8
>>!R!FONT62;EXIT;Abs.: euroSOFT-WARE A-8010 Graz, Kastellfeldgasse 23
>>!R!FONT62;EXIT;────────────────────────────────────────────────────

>>&FUSS (0)
>> 
>>             FÄLLIGKEITSANALYSE:   MAHNSTUFE 1
>>────────────────────────────────────────────────────────────────────────────────
>>A- 8054 Pirka                                                                          ~1._FREI_1

