@echo off
REM Druckprogramme:           SYMASK oder Prefix      Source: MASK       FORM
    %1 %2  SY4100 02000    ú  Druck Mandantenstamm    SY4041             SY1200   0010
rem %1 %2  SY4100 04000    ú  Druck Menzeilen        SY4020,020         SY4020   0010
REM           ³     ³                                                               ³
REM Programm ÄÙ     ÀÄÄ Steuerkennzeichen                        Formular-Nummer ÄÄÄÙ


