                                                  ÚÄÄÄ¿
                                                  ³   ³
                        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ   ÀÄÄÄÙ
 
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Adresse                            ³ Telefon
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
                                   ³   
Firma 2i Industrial Informatics Gm ³
Haierweg 20 e                      ³
D - 7800 Freiburg i.Br.            ³ 0761/4 22 57
                                   ³   
Firma A-Consult EDV-Beratungs-GmbH ³
K„rntnerstraáe 1                   ³
A - 1010 Wien                      ³ 0222/513 32 33, 51
                                   ³   
Firma A.C.O.                       ³
Computer Systeme GmbH              ³
Pfingstrosenstraáe 29              ³
D - 8000 Mnchen 70                ³ 089/714 09 05-08
                                   ³   
Firma a.h.c. managementberatungs g ³
austrian hotelconsult              ³
Schloá Rif                         ³
A - 5400 Hallein                   ³ 06245/55 46-0
                                   ³   
Firma A.P.S.                       ³
Automatic Portfolio Systems        ³
Rintheimerstraáe 11                ³
D - 7500 Karlsruhe 1               ³ 0721/69 18 17
                                   ³   
Firma AB Computergesellschaft m.b. ³
Wiedner Hauptstraáe 135            ³
A - 1050 Wien                      ³ 0222/55 16 30, 55 
                                   ³   
Firma abacomp-software             ³
Busdorfmauer 10                    ³
D - 4790 Paderborn                 ³ 05251/2 78 99
                                   ³   
Firma abacus computer gmbH         ³
Weilimdorfer Straáe 47             ³
D - 7015 Korntal-Mnchingen 1      ³ 0771/83 10 03
                                   ³   
Firma Abacus Software GmbH         ³
Berggasse 17, Stg. 2               ³
A - 1170 Wien                      ³ 0222/31 25 36-0
                                   ³   
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
