ÚÙLISTE KONSTANTEN                                    Datum: 05.09.90 - SEITE 0001À¿
³ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿³
À´Mandant (01) ...euroSOFT-WARE - 8010 Graz                        Teilnehmer: 002ÃÙ
 ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

 
Steuer-S„tze:
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Steuersatz 1 :  20,00 %                Steuersatz 5 :   0,00 %
Steuersatz 2 :  10,00 %                Steuersatz 6 :   0,00 %
Steuersatz 3 :  32,00 %                Steuersatz 7 :   0,00 %
Steuersatz 4 :   0,00 %                Steuersatz 8 :   0,00 %

 
Versandarten:
ÄÄÄÄÄÄÄÄÄÄÄÄÄ
Versandart 1 :  Bahn express           Versandart 4 :
Versandart 2 :  Post                   Versandart 5 :
Versandart 3 :  LKW frei Haus          Versandart 6 :

 
Werbetexte Zeile 1-4:
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
...euroSOFT-WARE!  -  Know-How fr L”sungen auf Einplatz- und Mehrplatzsystemen.

                                    Bankverb.:   CA - Griesplatz  -  A-8020 Graz
                                    Bankleitzahl:  11870,   Konto: 0188-34846/00

 
Nummernkreise:
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Stammdaten:      Kunden        :  500-1385
                 Lieferanten   :  100-0000
                 Artikel       :  900-006
                 Mitarbeiter   :  106
 
Bewegungsdaten:  Angebote      :  135
                 Auftr„ge      :  106
                 Lieferscheine :  100
                 Rechnungen    :  140
 
 
Landesw„hrung:   ™S
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
 
Artikel-Preis-Texte
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Artikel-Preis-Text 1 : H„ndler EKP     Artikel-Preis-Text 4 : 
Artikel-Preis-Text 2 : empf. VKP       Artikel-Preis-Text 5 :
Artikel-Preis-Text 3 : 


ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
À¿Nutzungsberechtigung: euroSOFT Graz                            (c) 1990 euroSOFTÚÙ
