粕LISTE FREMDW랧RUNG                                  Datum: 05.09.90 - SEITE 0001읏
넬컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴엿
윱Mandant (01) ...euroSOFT-WARE - 8010 Graz                        Teilnehmer: 002쵬
 읕컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴켸
 
                                       Bez.  Einheit   Kurs
                  컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
                  Fremdw꼑rung 1 :     셎            =   0,000

                  Fremdw꼑rung 2 :     DM    1       =   7,000

                  Fremdw꼑rung 3 :     Lire  100     =   1,000

                  Fremdw꼑rung 4 :                   =   0,000

                  Fremdw꼑rung 5 :                   =   0,000

                  Fremdw꼑rung 6 :                   =   0,000

                  Fremdw꼑rung 7 :                   =   0,000

                  Fremdw꼑rung 8 :                   =   0,000

                  Fremdw꼑rung 9 :                   =   0,000

                  Fremdw꼑rung 10:                   =   0,000
 

旼컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴커
읏Nutzungsberechtigung: euroSOFT Graz                            (c) 1990 euroSOFT粕
