@echo off
if exist case_01.exe del case_01.exe
if exist case_01.lzh del case_01.lzh
lharc a /x case_01.lzh !

    lharc a /x case_01.lzh F:\euro\exe\global.bc
    lharc a /x case_01.lzh F:\euro\bin\routine.dat
    lharc a /x case_01.lzh F:\euro\bin\msc.bat
    lharc a /x case_01.lzh F:\euro\bin\ask.exe
    lharc a /x case_01.lzh F:\euro\t01\c*.lnk
    lharc a /x case_01.lzh F:\euro\bin\app.bat
    lharc a /x case_01.lzh F:\euro\bin\eur.bat

    lharc a /x case_01.lzh F:\euro\bin\bchk.*
    lharc a /x case_01.lzh F:\euro\t01\tools.ini
    lharc a /x case_01.lzh F:\euro\bin\m.exe
    lharc a /x case_01.lzh F:\euro\bin\ws.zxt
    lharc a /x case_01.lzh F:\euro\bin\bat2*.*
    lharc a /x case_01.lzh F:\euro\bat\*.B
    lharc a /x case_01.lzh F:\euro\ini\*.B
    lharc a /x case_01.lzh F:\euro\bin\T01.bat
    lharc a /x case_01.lzh F:\euro\bin\ID.COM
    lharc a /x case_01.lzh F:\euro\bin\AP.COM
    lharc a /x case_01.lzh F:\euro\bin\K.COM
    lharc a /x case_01.lzh F:\euro\bin\ART.COM
    lharc a /x case_01.lzh F:\euro\bin\TE.BAT
    lharc a /x case_01.lzh F:\euro\bin\T.BAT
    lharc a /x case_01.lzh F:\euro\t01\FF.BAT
    lharc a /x case_01.lzh F:\euro\bin\B.COM
    lharc a /x case_01.lzh F:\euro\bin\ED.COM
    lharc a /x case_01.lzh F:\euro\bin\DATA.BAT
    lharc a /x case_01.lzh F:\euro\bin\DOC.COM
    lharc a /x case_01.lzh F:\euro\bin\EDI.COM
    lharc a /x case_01.lzh F:\euro\bin\I.COM
    lharc a /x case_01.lzh F:\euro\bin\MM*.BAT
    lharc a /x case_01.lzh F:\euro\bin\TEST.BAT
    lharc a /x case_01.lzh F:\euro\bin\BILDWORD.BAT
    lharc a /x case_01.lzh F:\euro\bin\HCOPY.BAT
    lharc a /x case_01.lzh F:\euro\bin\RE.COM
    lharc a /x case_01.lzh F:\euro\bin\C.COM
    lharc a /x case_01.lzh F:\euro\bin\COM.COM
    lharc a /x case_01.lzh F:\euro\bin\DRUCK.COM
    lharc a /x case_01.lzh F:\euro\bin\EXT.COM
    lharc a /x case_01.lzh F:\euro\bin\LPT.COM
    lharc a /x case_01.lzh F:\euro\bin\OUT.COM

    lharc a /x case_01.lzh F:\euro\mask\*.bat

    lharc a /x case_01.lzh F:\euro\c\ba*.obj
    lharc a /x case_01.lzh F:\euro\c\ma*.obj
    lharc a /x case_01.lzh F:\euro\c\db*.obj
    lharc a /x case_01.lzh F:\euro\c\dl*.obj
    lharc a /x case_01.lzh F:\euro\c\fo*.obj

    lharc a /x case_01.lzh F:\euro\include\eur_*.h
    lharc a /x case_01.lzh F:\euro\include\app_*.h
    lharc a /x case_01.lzh F:\euro\c\*.h

    lharc a /x case_01.lzh F:\euro\c\sy1100
    lharc a /x case_01.lzh F:\euro\c\sy_1100.cpp
    lharc a /x case_01.lzh F:\euro\c\sy1100.cpp
    lharc a /x case_01.lzh F:\euro\c\sy4100
    lharc a /x case_01.lzh F:\euro\c\sy_4100.cpp
    lharc a /x case_01.lzh F:\euro\c\sy4100.cpp
    lharc a /x case_01.lzh F:\euro\c\sy4100a.cpp
    lharc a /x case_01.lzh F:\euro\c\st1100
    lharc a /x case_01.lzh F:\euro\c\st_1100.cpp
    lharc a /x case_01.lzh F:\euro\c\st1100.cpp
    lharc a /x case_01.lzh F:\euro\c\st1100a.cpp
    lharc a /x case_01.lzh F:\euro\c\st4100
    lharc a /x case_01.lzh F:\euro\c\st_4100.cpp
    lharc a /x case_01.lzh F:\euro\c\st4100.cpp
    lharc a /x case_01.lzh F:\euro\c\st4100a.cpp
    lharc a /x case_01.lzh F:\euro\c\fibasis.cpp
    lharc a /x case_01.lzh F:\euro\c\fi_1100.cpp
    lharc a /x case_01.lzh F:\euro\c\fi1100.cpp
    lharc a /x case_01.lzh F:\euro\c\fi1100a.cpp
    lharc a /x case_01.lzh F:\euro\c\fi_4100.cpp
    lharc a /x case_01.lzh F:\euro\c\fi4100.cpp
    lharc a /x case_01.lzh F:\euro\c\fi4100a.cpp
    lharc a /x case_01.lzh F:\euro\lib\???_M70L.LIB

lharc s /x case_01.lzh
if exist case_01.lzh del case_01.lzh

