@echo off
if exist EU_10.exe del EU_10.exe
if exist EU_10.lzh del EU_10.lzh
lharc a /x EU_10.lzh !

rem lharc a /x eu_10.lzh f:\euro\mask\sy\sym*.
rem lharc a /x eu_10.lzh f:\euro\form\sy\syf*.m

    lharc a /x eu_10.lzh x:\euro\bin\t02.bat
    lharc a /x eu_10.lzh x:\euro\bin\ed.bat
    lharc a /x eu_10.lzh x:\euro\bin\mm.bat
    lharc a /x eu_10.lzh x:\euro\bin\mf.bat

    lharc a /x eu_10.lzh f:\euro\dat\euform.043
    lharc a /x eu_10.lzh f:\euro\dat\a10110.seq
    lharc a /x eu_10.lzh f:\euro\dat\a10120.seq
    lharc a /x eu_10.lzh f:\euro\dat\a10130.seq
    lharc a /x eu_10.lzh f:\euro\dat\a10110.lex
    lharc a /x eu_10.lzh f:\euro\dat\a10120.lex
    lharc a /x eu_10.lzh f:\euro\dat\a10130.lex
    lharc a /x eu_10.lzh f:\euro\dat\basis.lex

    lharc a /x eu_10.lzh f:\euro\hlp\eu*.043

    lharc a /x eu_10.lzh f:\euro\exe\bildega.exe
    lharc a /x eu_10.lzh f:\euro\exe\bildword.exe
    lharc a /x eu_10.lzh f:\euro\exe\euroinst.exe
    lharc a /x eu_10.lzh f:\euro\exe\katalog.exe

    lharc a /x eu_10.lzh f:\euro\exe\asc2euro.exe
    lharc a /x eu_10.lzh f:\euro\exe\fc.exe
    lharc a /x eu_10.lzh f:\euro\exe\mc.exe
    lharc a /x eu_10.lzh f:\euro\exe\eurodata.btr
    lharc a /x eu_10.lzh x:\euro\exe\edit.com
    lharc a /x eu_10.lzh x:\euro\t01\menu.exe

    lharc a /x eu_10.lzh f:\euro\exe\eu1100.exe
    lharc a /x eu_10.lzh f:\euro\exe\eu4100.exe
    lharc a /x eu_10.lzh f:\euro\exe\eumask.043


lharc s /x EU_10.lzh
if exist EU_10.lzh del EU_10.lzh


@echo off
if exist EU_10.exe del EU_10.exe
if exist EU_10.lzh del EU_10.lzh
lharc a /x EU_10.lzh !

lharc a /x eu_10.lzh f:\euro\exe\bildega.exe
lharc a /x eu_10.lzh f:\euro\exe\bildword.exe
lharc a /x eu_10.lzh f:\euro\exe\euroinst.exe
lharc a /x eu_10.lzh f:\euro\exe\katalog.exe

lharc a /x eu_10.lzh f:\euro\bin\t02.bat
lharc a /x eu_10.lzh f:\euro\bin\ed.bat
lharc a /x eu_10.lzh f:\euro\bin\mm.bat
lharc a /x eu_10.lzh f:\euro\bin\mf.bat
lharc a /x eu_10.lzh f:\euro\mask\st\stm110
lharc a /x eu_10.lzh f:\euro\form\st\stf1100.m

lharc a /x eu_10.lzh f:\euro\exe\asc2euro.exe
lharc a /x eu_10.lzh f:\euro\exe\fc.exe
lharc a /x eu_10.lzh f:\euro\exe\mc.exe

lharc a /x eu_10.lzh f:\euro\exe\eu1100.exe
lharc a /x eu_10.lzh f:\euro\exe\eu4100.exe
lharc a /x eu_10.lzh f:\euro\exe\eumask.043

lharc a /x eu_10.lzh f:\euro\dat\euform.043
lharc a /x eu_10.lzh f:\euro\dat\a10110.seq
lharc a /x eu_10.lzh f:\euro\dat\a10110.lex
lharc a /x eu_10.lzh f:\euro\dat\basis.lex

lharc a /x eu_10.lzh f:\euro\hlp\eu*.043

lharc s /x EU_10.lzh
if exist EU_10.lzh del EU_10.lzh



