  

1                        SideKick Installierungsmenü
2           Wählen Sie einen der folgenden Punkte zur Installierung:
è4          Monitor-Typ │ Notiz-Kommandos │  Notiz-Dateigröße │ Rechter Rand 

5          Modem       │ Farben          │ Aktivierungs-Kommandos │ Ende


6                    Geben Sie T, K, D, R, M, F, A oder E ein:

7  Doppelte Definition. Kommand Nr. 
8  Überschneidung mit einem nicht installierbaren Kommando
10 Doppelte Definition. Kommandos Nr. 
11 Kommandos mit gleichem Anfangsbchstaben müssen die gleiche Länge haben.
 Falsche Kommandos sind: 
12 Gesamtlänge aller Kommandos überschritten. Kürze ein oder mehrere Kommandos.
13  -> 


14 CURSORSTEUERUNG:

20  Zeichen links                    
21    Alternative                    
22  Zeichen rechts                   
23  Wort links                       
24  Wort rechts                      
25  Zeile nach oben                  
26  Zeile nach unten                 
27  Rollen aufwärts                  
28  Rollen abwärts                   
29  Seite nach oben                  
30  Seite nach unten                 
31  Linker Rand                      
32  Rechter Rand                     
33  Anfang der Seite                 
34  Ende der Seite                   
35  Anfang der Datei                 
36  Ende der Datei                   
37  Dateiende/Datum-Zeitvermerk      
38  Anfang eines Blocks              
39  Ende eines Blocks                
40  Letzte Cursorposition            


15 EINFÜGEN & LÖSCHEN:

41  Einfügen-Modus ein/aus           
42  Zeile einfügen                   
43  Zeile löschen                    
44  Löschen bis Zeilenende           
45  Wort rechts löschen              
46  Zeichen unter Cursor löschen     
47  Zeichen links löschen            
48    Alternative                    

16 BLOCK KOMMANDOS:

49  Blockanfang markieren            è50  Blockende markieren              
51  Wort markieren                   
52  Block verdecken/zeigen           
53  Block kopieren                   
54  Block verschieben                
55  Block löschen                    
56  Block von Disk lesen             
57  Block auf Disk schreiben         
58  Block sortieren                  
59  Block drucken                    
60  Block einfügen                   
 
17  VERSCHIEDENE KOMMANDOS:

61  Notiz-File sichern               
62  Tab                              
63  Letzte Suche wiederholen         
64  Kontrollzeichen-Präfix           
65  Suchen                           
66  Suchen und Tauschen              
67  Auto Tabulator ein/aus           
68  Zeile wiederherstellen           
69  Datum/Zeit eintragen             
70  Graphik ein/aus                  
71  Setzen des rechten Rands         
72  Abschnitt neuformatieren         

80 Größe des Notiz-Files (1000-50000 Zeichen, ─┘ keine Änderung): 
81 Modemschnittstelle (1 für Com1:  2 für Com2:) (─┘ kein Modem): 
82 Blinkt der Bildschirm beim Textrollen (Y/N) (─┘  keine Änderung): 
83 Voreinstellung in den Notizen für den rechten Rand (Spalte 1-251, ─┘ keine Änderung) 
85 Geben Sie H ein um eines der folgenden Modems zu wählen :
86          oder ein anderes Hayes-kompatibles Modem (300 Baud)
87 Geben Sie J ein um das IBM PCjr Modem zu wählen (300 Baud)
88 Ausgewähltes Modem (H/J/V/A, ─┘ keine Änderung): 
89 Minimale Ziffern-Zahl (1-80, ─┘  keine Änderung): 
90 Gewünschtes Zeichen (bis zu 10 Zeichen,  ─┘ keine Änderung)
91 Geben Sie V ein um das VOAD Tasten-Telefon zu wählen (9600 Baud)
92 Geben Sie A um ein AT & T 4000 Modem zu wählen (1200 Baud) 
101 Nichts

120 Borland Produkt-Upgrade-System
121 Produkt-Upgrade erstellt
122 Weiter mit <RETURN> :
123 Fehler im Eingabe-File :
124 Syntaxfehler
125 File für Update nicht gefunden :
126 Update-Sheet paßt nicht zum aktuellen File
127 Falsches File (File zu klein) oder Syntaxfehler
128 Filename eingeben
129 Prüfsumme unkorrekt
130 Eingabe-File FI    existiert nicht
131 Zuviel Eingabe oder Syntaxfehler
132 Zuviele Bytes in einer Zeile
133 Alte und neue Zeile stimmen nicht überein

150 Wollen Sie die Installierung durchführen
151 (Y/N): 
152 Programm-Files von den  Notizen nicht geöffnet

200 Wählen Sie den Darstellungsmodus
201 Welchen Darstellungsmodus (Eingabe der Nummer oder "Q" zum Quittieren): 
202 voreingestellter Darstellungsmodus
203 Monochrome Darstellung
204 Farb-Darstellung 80x25
205 Schwarz/Weiß-Darstellung 80x25

è   
