粕KOSTENSTELLEN/KOSTENARTEN-LISTE                     Datum: 04.09.90 - SEITE 0001읏
넬컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴엿
윱Mandant (01) ...euroSOFT-WARE - 8010 Graz                        Teilnehmer: 002쵬
 읕컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴켸
          Kostenstelle      Budget in T셎  Mon.01 Mon.02 Mon.03 Mon.04 Mon.05 Mon.06
Nummer    Kostenart                        Mon.07 Mon.08 Mon.09 Mon.10 Mon.11 Mon.12
컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
T1000     Kost 1                            10.00  10.00  10.00  10.00  10.00  10.00
S8100     Erl봲e 20% MWST                   10.00  10.00  10.00  10.00  10.00  10.00
컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴



旼컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴커
읏Nutzungsberechtigung: euroSOFT Graz                            (c) 1990 euroSOFT粕
