
     粕BUCHUNGSERFASSUNGS-PROTOKOLL                                                          Datum: 16.03.91 - SEITE 0001읏
     넬컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴엿
     윱Mandant (03) ... T갷htig & Co                                                                      Teilnehmer: 002쵬
      읕컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴켸
            Buch.-   Soll-     Beleg-     Beleg-   Haben-                                                 U U
     Lfd.Nr    Datum konto     Nummer        Datum Konto             Betrag Buchungstext                  A S    UST-Betrag
     컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
      
     000001  3.04.91 S2000     KO/001      3.04.91 S2100          10.000,00 KO Umbuchungen                  0          0,00
     000002  3.04.91 K105      EB/001      3.04.91 S9700           1.000,00 EB Saldovortrag Kunden        m 0          0,00
     000003  3.04.91 K105      VK/001      3.04.91 S8200           1.200,00 VK Rechnungsausgang           m 2        200,00
     000004  3.04.91 S2100     VK/002      3.04.91 K105            1.200,00 VK Zahlungseingang              0          0,00
     000005  3.04.91 S9700     EB/002      3.04.91 L113            1.000,00 EB Saldovortrag Lieferanten   v 0          0,00
     000006  3.04.91 S4120     EK/001      3.04.91 L113            1.200,00 EK Rechnungseingang           v 2        200,00
     000007  3.04.91 L113      EK/002      3.04.91 S2100           1.200,00 EK Zahlungsausgang              0          0,00
     000008  3.04.91 S9700     EB/004      3.04.91 S2100           1.000,00 EB Schkonto Haben               0          0,00
     000009  3.04.91 S1100     EB/003      3.04.91 S9700           1.000,00 EB Sachkonto Soll               0          0,00
     000010  3.04.91 S2000     BA/002      3.04.91 S8200           1.200,00 BA Barverkauf                 m 2        200,00
     000011  3.04.91 S4120     BA/001      3.04.91 S2000           1.200,00 BA Bareinkauf                 v 2        200,00


     旼컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴커
     읏Nutzungsberechtigung: euroSOFT Graz                                                              (c) 1990 euroSOFT粕


