粕BILANZ-AUSWERTUNG                                                                     Datum: 04.09.90 - SEITE 0001읏
넬컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴엿
윱Mandant (01) ...euroSOFT-WARE - 8010 Graz                                                          Teilnehmer: 002쵬
 읕컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴켸
Text                                         Wert          Gruppen-Summe       Zwischen-Summe            Gesamt-Summe
컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
                                   ###.###.###,##         ###.###.###,##       ###.###.###,##          ###.###.###,##
A U F W E N D U N G E N
                                        
  1. WARENEINSATZ
    Wareneinsatz (Hilfsstoffe)     ###.###.###,##
                                                          ###.###.###,##

  2. BETRIEBSKOSTEN
    Energiebez갾e                  ###.###.###,##
    Miete                          ###.###.###,##
    KFZ-Kosten                     ###.###.###,##
    Instandhaltungen               ###.###.###,##
                                                          ###.###.###,##
  3. PERSONALKOSTEN
    Geh꼕ter                       ###.###.###,##
    Werksvertr꼏e/Provisionen      ###.###.###,##
    Gesetzl. Sozialaufwand         ###.###.###,##
    DB und DZ                      ###.###.###,##
                                                          ###.###.###,##
                                                                               ###.###.###,##
  4. STEUERN, VERSICHERUNGEN
    Sonstige Geb갿ren/Abgaben      ###.###.###,##
                                                          ###.###.###,##
  5. VERWALTUNG UND VERTRIEB
    Telefongeb갿ren                ###.###.###,##
    Postgeb갿ren, Marken           ###.###.###,##
    Werbeaufwand, Messen           ###.###.###,##
    B걊oaufwand                    ###.###.###,##
    Reisesp., Kurse, Tagungen      ###.###.###,##
    Fachliteratur                  ###.###.###,##
    Rechts- u. Beratungskosten     ###.###.###,##
    Sonstiger Sachaufwand          ###.###.###,##
                                                          ###.###.###,##
  6. ZINSEN KREDIT- U. BANKSP.
    Kreditspesen und -geb갿ren     ###.###.###,##
                                                                               ###.###.###,##
  7. KUNDENSKONTI
    Skontoaufwand 20% MWST         ###.###.###,##
                                                          ###.###.###,##
                                                                               ###.###.###,##
  8. ABSCHREIB. V. ANLAGEVERM.
    Geringw. Wirtschaftsg걎er      ###.###.###,##
                                                          ###.###.###,##
                                                                               ###.###.###,##

                                                                                                       ###.###.###,##

旼컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴커
읏Nutzungsberechtigung: euroSOFT Graz                                                              (c) 1990 euroSOFT粕
