粕BILANZ-AUSWERTUNG                                                                     Datum: 04.09.90 - SEITE 0001읏
넬컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴엿
윱Mandant (01) ...euroSOFT-WARE - 8010 Graz                                                          Teilnehmer: 002쵬
 읕컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴켸
Text                                         Wert          Gruppen-Summe       Zwischen-Summe            Gesamt-Summe
컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
P A S S I V A

  I. KAPITAL                       ###.###.###,##
                                                          ###.###.###,##
                                                                               ###.###.###,##
  II. INVESTITIONSFREIBETRAG
                                                          ###.###.###,##
                                                                               ###.###.###,##
  III. R숦KSTELLUNGEN
                                                          ###.###.###,##
                                                                               ###.###.###,##
  IV. VERBINDLICHKEITEN
    Lieferantenverbindlichk.       ###.###.###,##
    Verbindl. Finanzamt            ###.###.###,##
    Sonstige Verbindlichkeiten     ###.###.###,##
                                                          ###.###.###,##
                                                                               ###.###.###,##


      Vorl. Bilanzgewinn                                                                               ###.###.###,##

      Bilanzsumme                                                                                      ###.###.###,##


旼컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴커
읏Nutzungsberechtigung: euroSOFT Graz                                                              (c) 1990 euroSOFT粕
