┌┘SACHKONTEN-LISTE                                    Datum: 04.09.90 - SEITE 0001└┐
│┌────────────────────────────────────────────────────────────────────────────────┐│
└┤Mandant (01) ...euroSOFT-WARE - 8010 Graz                        Teilnehmer: 002├┘
 └────────────────────────────────────────────────────────────────────────────────┘
Konto-                                UStVa USt Sammel Kto. KSt.  Ausw.-Kz  Ausw.-Kz
Nummer    Bezeichnung                  -Kz  -Kz  -Kz   -Art -Kz      Soll     Haben
────────────────────────────────────────────────────────────────────────────────────
S0200     Maschinen                         20.00 nein Bila nein    AK110
S0300     Werkzeuge u. Geräte               20.00 nein Bila nein    AK110
S0400     Betriebs u. Geschäftsausstattu    20.00 nein Bila nein    AK120
S0490     Geringw. Wirtschaftsgüter         20.00 nein Betr nein    AU830
S0500     Fuhrpark                          20.00 nein Bila nein    AK130
S0700     Rechte, Programmlizenzen          20.00 nein Bila nein    AK150
S0800     Beteiligungen u. Wertpap.               nein Bila nein    AK150
S1100     Handelswarenvorräte                     nein Bila nein    AK210
S1900     Wertberrichtigung Vorräte               nein Bila nein    AK210
S2000     Kassa                                   nein Bila nein    AK225
S2100     CA - Graz                               nein Bila nein    AK230     PA420
S2180     Scheckverrechnung                       nein Bila nein    AK260
S2190     Geldtransitkonto                        nein Bila nein    AK260     PA450
S2200     Geld im Umlauf                          nein Bila nein    AK260
S2300     Forderungen Inland                      ja   Bila nein    AK220
S2310     Forderungen Ausland                     ja   Bila nein    AK220
S2400     Guthaben bei Lieferanten                nein Bila nein    AK240
S2410     Anzahlungen, Kautionen                  nein Bila nein    AK240
S2500     Vorsteuer-Konto               50        nein Bila nein    AK250     PA445
S2510     EUST                          60        nein Bila nein    AK250     PA445
S2600     Verrechnungsvorschüsse                  nein Bila nein    AK260
S2710     Lohn- u. Gehaltsvorschüsse              nein Bila nein    AK260
S2800     Aktive Rechnungsabgrenzung              nein Bila nein    AK310
S3300     Verbindlichkeiten Inland                nein Bila nein              PA410
S3310     Verbindlichkeiten Ausland               nein Bila nein              PA410
S3500     Verbindlichk. Finanzamt                 nein Bila nein    AK250     PA445
S3510     Mehrwertsteuer 20%            41        nein Bila nein    AK250     PA445
S3520     Mehrwertsteuer 10%            42        nein Bila nein    AK250     PA445
S3530     Mehrwertsteuer 32%            43        nein Bila nein    AK250     PA445
S3540     Mehrwertsteuer 10% Reisek.    40        nein Bila nein    AK250     PA445
S3580     Gemeinde Graz, LSSt.                    nein Bila nein    AK260     PA450
S3590     Finanzamt Lohnsteuer                    nein Bila nein    AK250     PA445
S3600     Durchlaufkonto Lohnverrg.               nein Bila nein    AK260     PA450
S3630     Darlehen                                nein Bila nein              PA450
S3650     Stmk. Gebietskrankenkasse               nein Bila nein              PA450
S3700     Rückst. Gründungskosten                 nein Bila nein              PA330
S3710     Rückst.Rechts-u.Berat.Kost              nein Bila nein              PA320
S3800     Passive Rechnungsabgrenz.               nein Bila nein              PA510
S3900     Sonstige Verbindlichkeiten              nein Bila nein              PA450
S4100     Wareneinkauf Inland               20.00 nein Eink nein    AU120
S4110     Wareneinkauf Ausland              20.00 nein Eink nein    AU120
S4120     Bezugssp./Fracht - Inland         20.00 nein Eink nein    AU130
S4130     Bezugssp./Fracht - Ausland        20.00 nein Eink nein    AU130
S4190     Wertberr. Wareneinkauf            20.00 nein Eink nein    AU120
S4400     Verbrauch von Hilfsstoffen        20.00 nein Eink nein    AU120
S4600     Energie Strom/Gas                 20.00 nein Betr nein    AU220
S4650     Leasing, Aufwand PKW rot                nein Tran nein    AU240
S4660     Leasing, Aufwand PKW schw.              nein Tran nein    AU240
S4670     Aufwand Leihwagen                       nein Tran nein    AU240
S4690     Versicherungen KFZ                      nein Tran nein    AU240
S4700     Verpackungsmaterial               20.00 nein Kost nein    AU580
S4900     Fremdarbeit                       20.00 nein Eink nein    AU135
S5100     Reisekosten, Diäten                     nein Pers nein    AU550
S5330     Gehälter Angestellte                    nein Pers nein    AU320
S5350     Lehrlingsentschädigung                  nein Pers nein    AU320

┌──────────────────────────────────────────────────────────────────────────────────┐
└┐Nutzungsberechtigung: euroSOFT Graz                            (c) 1990 euroSOFT┌┘
