┌┘BILANZ-TEXTE                                        Datum: 04.09.90 - SEITE 0001└┐
│┌────────────────────────────────────────────────────────────────────────────────┐│
└┤Mandant (01) ...euroSOFT-WARE - 8010 Graz                        Teilnehmer: 002├┘
 └────────────────────────────────────────────────────────────────────────────────┘
Kennz.  ART    TEXT
────────────────────────────────────────────────────────────────────────────────────
        Text    A K T I V A
        Text
        Text      I. ANLAGEVERMÖGEN
AK110   Wert        Maschinen, Geräte
AK120   Wert        Betriebs- u. Geschäftsaus.
AK130   Wert        Fahrzeuge
AK140   Wert        Gebäude
AK150   Wert        Rechte und Beteiligungen
        Grup
        Text      II. UMLAUFVERMÖGEN
AK210   Wert        Vorräte
AK220   Wert        Kundenforderungen
AK225   Wert        Kassenbestand
AK230   Wert        Bankguthaben
AK240   Wert        Anzahlungen, Kautionen
AK245   Wert        Verrechnung Inhaber
AK250   Wert        Forderungen Finanzamt
AK260   Wert        Sonstige Forderungen
        Grup
        Zwis
AK310   Wert      III. AKT. RECHNUNGSABGRENZ.
        Grup
        Zwis
AK410   Wert      IV. VERLUSTVORTRAG
        Grup
        Zwis
AK990   Summ
AK999   Vors

┌──────────────────────────────────────────────────────────────────────────────────┐
└┐Nutzungsberechtigung: euroSOFT Graz                            (c) 1990 euroSOFT┌┘
