粕BILANZ-TEXTE                                        Datum: 04.09.90 - SEITE 0001읏
넬컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴엿
윱Mandant (01) ...euroSOFT-WARE - 8010 Graz                        Teilnehmer: 002쵬
 읕컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴켸
Kennz.  ART    TEXT
컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
        Text    A K T I V A
        Text
        Text      I. ANLAGEVERM섻EN
AK110   Wert        Maschinen, Ger꼝e
AK120   Wert        Betriebs- u. Gesch꼎tsaus.
AK130   Wert        Fahrzeuge
AK140   Wert        Geb꼞de
AK150   Wert        Rechte und Beteiligungen
        Grup
        Text      II. UMLAUFVERM섻EN
AK210   Wert        Vorr꼝e
AK220   Wert        Kundenforderungen
AK225   Wert        Kassenbestand
AK230   Wert        Bankguthaben
AK240   Wert        Anzahlungen, Kautionen
AK245   Wert        Verrechnung Inhaber
AK250   Wert        Forderungen Finanzamt
AK260   Wert        Sonstige Forderungen
        Grup
        Zwis
AK310   Wert      III. AKT. RECHNUNGSABGRENZ.
        Grup
        Zwis
AK410   Wert      IV. VERLUSTVORTRAG
        Grup
        Zwis
AK990   Summ
AK999   Vors

旼컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴커
읏Nutzungsberechtigung: euroSOFT Graz                            (c) 1990 euroSOFT粕
