 
┌┘UMSATZSTEUER-VORANMELDUNG                                  Datum: 16.03.91 └┐
│┌───────────────────────────────────────────────────────────────────────────┐│
└┤Mandant (03) ... Tüchtig & Co                               Teilnehmer: 002├┘
 └───────────────────────────────────────────────────────────────────────────┘
 
 
 
 Gesamtbetrag der steuerpflichtigen Umsätze:          2.000
 
 
 Davon zu versteuern:
 ────────────────────
 
 Mit 10,00% Mehrwertsteuer                                0               0,00
 Mit 20,00% Mehrwertsteuer                            2.000             400,00
 Mit 32,00% Mehrwertsteuer                                0               0,00
 Mit  0,00% Mehrwertsteuer                                0               0,00
 Mit  0,00% Mehrwertsteuer                                0               0,00
 ─────────────────────────────────────────────────────────────────────────────
            Summe  Umsatzsteuer                                         400,00
 
 
            - Vorsteuer                                 400,00
            - EUST                                        0,00
            - MwSt-Korrektur                              0,00          400,00
            ──────────────────────────────────────────────────────────────────
            * Zahllast (Gutschrift bei -Betrag)                           0,00
            ──────────────────────────────────────────────────────────────────
 
 
 
 
 
 
 
 
 Umsatzsteuer Verprobung:
 ────────────────────────
 
 Steuer gemäß:              Berechnung          MwSt-Konto           Differenz
 ─────────────────────────────────────────────────────────────────────────────
 Steuergruppe 10,00%              0,00                0,00                0,00
 Steuergruppe 20,00%            400,00             -400,00                0,00
 Steuergruppe 32,00%              0,00                0,00                0,00
 Steuergruppe  0,00%              0,00                0,00                0,00
 Steuergruppe  0,00%              0,00                0,00                0,00
 ─────────────────────────────────────────────────────────────────────────────
 Gesamt                         400,00             -400,00                0,00
 ─────────────────────────────────────────────────────────────────────────────



┌─────────────────────────────────────────────────────────────────────────────┐
└┐Nutzungsberechtigung: euroSOFT Graz                       (c) 1990 euroSOFT┌┘

