┌┘BILANZ-AUSWERTUNG                                                                     Datum: 04.09.90 - SEITE 0001└┐
│┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐│
└┤Mandant (01) ...euroSOFT-WARE - 8010 Graz                                                          Teilnehmer: 002├┘
 └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Text                                         Wert          Gruppen-Summe       Zwischen-Summe            Gesamt-Summe
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
A K T I V A
                                        
  I. ANLAGEVERMÖGEN
    Inventar                       ###.###.###,##
                                                          ###.###.###,##

  II. UMLAUFVERMÖGEN
    Kundenforderungen              ###.###.###,##
    Kassenbestand                  ###.###.###,##
    Bankguthaben                   ###.###.###,##
    Verrechnung Inhaber            ###.###.###,##
    Forderungen Finanzamt          ###.###.###,##
    Sonstige Forderungen           ###.###.###,##-
                                                          ###.###.###,##
                                                                               ###.###.###,##


      Bilanzsumme                                                                                      ###.###.###,##


 
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└┐Nutzungsberechtigung: euroSOFT Graz                                                              (c) 1990 euroSOFT┌┘
