┌┘BILANZ-AUSWERTUNG                                                                     Datum: 04.09.90 - SEITE 0001└┐
│┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐│
└┤Mandant (01) ...euroSOFT-WARE - 8010 Graz                                                          Teilnehmer: 002├┘
 └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Text                                         Wert          Gruppen-Summe       Zwischen-Summe            Gesamt-Summe
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                   ###.###.###,##         ###.###.###,##       ###.###.###,##          ###.###.###,##
A U F W E N D U N G E N
                                        
  1. WARENEINSATZ
    Wareneinsatz (Hilfsstoffe)     ###.###.###,##
                                                          ###.###.###,##

  2. BETRIEBSKOSTEN
    Energiebezüge                  ###.###.###,##
    Miete                          ###.###.###,##
    KFZ-Kosten                     ###.###.###,##
    Instandhaltungen               ###.###.###,##
                                                          ###.###.###,##
  3. PERSONALKOSTEN
    Gehälter                       ###.###.###,##
    Werksverträge/Provisionen      ###.###.###,##
    Gesetzl. Sozialaufwand         ###.###.###,##
    DB und DZ                      ###.###.###,##
                                                          ###.###.###,##
                                                                               ###.###.###,##
  4. STEUERN, VERSICHERUNGEN
    Sonstige Gebühren/Abgaben      ###.###.###,##
                                                          ###.###.###,##
  5. VERWALTUNG UND VERTRIEB
    Telefongebühren                ###.###.###,##
    Postgebühren, Marken           ###.###.###,##
    Werbeaufwand, Messen           ###.###.###,##
    Büroaufwand                    ###.###.###,##
    Reisesp., Kurse, Tagungen      ###.###.###,##
    Fachliteratur                  ###.###.###,##
    Rechts- u. Beratungskosten     ###.###.###,##
    Sonstiger Sachaufwand          ###.###.###,##
                                                          ###.###.###,##
  6. ZINSEN KREDIT- U. BANKSP.
    Kreditspesen und -gebühren     ###.###.###,##
                                                                               ###.###.###,##
  7. KUNDENSKONTI
    Skontoaufwand 20% MWST         ###.###.###,##
                                                          ###.###.###,##
                                                                               ###.###.###,##
  8. ABSCHREIB. V. ANLAGEVERM.
    Geringw. Wirtschaftsgüter      ###.###.###,##
                                                          ###.###.###,##
                                                                               ###.###.###,##

                                                                                                       ###.###.###,##

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
└┐Nutzungsberechtigung: euroSOFT Graz                                                              (c) 1990 euroSOFT┌┘
