@echo off
dir be%1*.* /p /o:ne
echo.
echo           ---------------------------
echo   [31m   ... und noch dazu \euro\exe   [0m
echo           ---------------------------
echo.
pause
dir \euro\exe\be%1*.* /p /o:ne
echo.
echo           ---------------------------
echo   [31m   ... und weiters	 \euro\t04   [0m
echo           ---------------------------
echo.
pause
dir \euro\t04\be%1*.* /p /o:ne
