!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                   II. Bereich: Auftrag... / 1.1
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
º  WINware Gro¨e Auftragsbearbeitung                                                º
ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼

!R!FTMD13;FONT50080;SLS.122;EXIT;
!R!FTMD13;FONT50055;SLS.142;EXIT;
  Men§leiste ¯Gro¨e Auftragsbearbeitung®:
  ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50080;SLS.122;EXIT;
  ÚÄÄÄÄÄÄÄÄÄÄÄÄ¿              ÚÄÄÄÄÄÄÄ¿                 ÚÄÄÄÄÄÄÄÄÄÄÄÄ¿                ÚÄÄÄÄÄÄÄÄ¿                 
  ³ Auftrag... ³              ³ Lager ³                 ³ Auswertung ³                ³ Zusatz ³                 
  ÃÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄ¿  ÃÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿  ÃÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄ¿  ÃÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³ Angebote/Rechnungen... ³  ³ Lagerbewegungen      ³  ³ Umsatz...                ³  ³ Inventur...             ³
  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´  ³ Protokoll Bewegungen ³  ³ Umsatz Vorjahresvergl... ³  ³ Kartei...               ³
  ³ Auftragseingangsbuch   ³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´  ³ Zuschlagskalkulation... ³
  ³ Rechnungsausgangsbuch  ³  ³ Druck Mindestbestand ³  ³ Periodenabschlu¨         ³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´  ³ Druck Artikelnummer  ³  ³ Jahresabschlu¨           ³  ³ Barverkauf/Kasse...     ³
  ³ Statistiklauf          ³  ³ Druck Hersteller     ³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´  ³ Barcode Etiketten...    ³
  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´  ³ Tagessummen              ³  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
                              ³ Bestellwesen...      ³  ³ Interne Rechnungen       ³  ³ Reparaturverwaltung...  ³
                              ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ  ³ Gew¥hrleistungen         ³  ³ Paketversand...         ³
                                                        ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ  ³ Seriennum.verwaltung... ³
                                                                                      ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
                                                                                      ³ Verwaltung OP's         ³
                                                                                      ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
!R!FTMD13;FONT50055;SLS.142;EXIT;
!R!FTMD13;FONT50080;SLS.122;EXIT;
!R!FTMD13;FONT50055;SLS.142;EXIT;
  Men§leiste ¯Gro¨e Auftragsbearbeitung®:
  ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50080;SLS.122;EXIT;
  ÚÄÄÄÄÄÄÄÄÄÄÄÄ¿              
  ³ Stammdaten ³              
  ÃÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³ ¢ndern Kundenstamm       ³
  ³ ¢ndern Lieferantenstamm  ³
  ³ ¢ndern Artikelstamm      ³
  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
  ³ Stammdaten/Konstanten... ³
  ³ Schnell¥nderungen...     ³
  ³ Preise&Rabatte...        ³
  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
  ³ ¢ndern Mitarbeiterstamm  ³
  ³ Liste Mitarbeiter        ³
  ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
  ³ Vertreterstamm           ³
  ³ Vertreterliste           ³
  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
!R!FTMD13;FONT50055;SLS.142;EXIT;
   ---------------------------------------------------


!R!FTMD13;FONT50080;SLS.122;EXIT;
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Men§fenster ¯Hauptmen§® / Auftrag... (AUF-001):Auftrag
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50080;SLS.122;EXIT;
   ÚÄÄÄÄÄÄÄÄÄÄÄÄ¿             
   ³ Auftrag... ³                ... Bearbeiten und drucken v. Auftr¥gen, Rechnungen u. Gutschriften.
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄ¿
   ³ Angebote/Rechnungen...  ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Auftragseingangsbuch    ³
   ³ Rechnungsausgangsbuch   ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Statistiklauf           ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
!R!FTMD13;FONT50055;SLS.142;EXIT;

!R!FTMD13;FONT50055;SLS.142;EXIT;
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                   II. Bereich: Auftrag... / 1.2
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;!R!FTMD13;FONT50055;SLS.142;EXIT;
   !R!FTMD13;FONT50055;SLS.142;EXIT;Ein-/Ausgabefelder f§r: Bearbeiten Angebote (AUFM200)
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Ú(c) 1993 WINware ÄÄÄÄÄ WINware P.Mayer / A-1040 Wien ÄÄÄÄÄ Datum 01.12.93 (01)¿
   À!R!FTMD13;FONT50255;EXIT;ğğF-TastenğğOptionenğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğF1=Hilfeğğğğ!R!FTMD13;FONT50055;SLS.142;EXIT;Ù
   ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄBearbeiten Angebote - 1/2Ä¿
   ³  Vorgang   :@@@@@@@@@@@@                   Nummer    :@@@@@@@@@@@@           ³
   ³                                                                              ³
   ³  Empf¥nger : D@@@@@@@@@@                   Vertreter       :@@@@@@@@@@@@@@   ³
   ³                                            Tour/Gebiet     :@@@@@@@@@@@@@@   ³
   ³  Name 1    :@@@@@@@@@@@@                   Preisgruppe     :@@@@@@@@@@@@@@   ³
   ³  Name 2    :@@@@@@@@@@@@                   Rabattgruppe    :@@@(0-8)         ³
   ³  Strasse   :@@@@@@@@@@@@                   Zahlungskond.   :@@@@@@@          ³
   ³  PLZ Ort   :@@@@@@@@@@@@                   USt.schl§ssel   :@@@@@@@          ³
   ³  Kurzbez.  :@@@@@@@@@@@@                   Rechnungskreis  :@@@(0-9)         ³
   ³                                            Rabattsatz      :@@@@@@@%         ³
   ³  Datum     :@@@@@@@@@@@@                   Provision       :@@@@@@@%         ³
   ³  Bearbeiter:@@@@@@@@@@@@                   W¥hrung         :@@@@@@@          ³
   ³  Versand   :@@@@@@@@@@@@                   Sprachcode      :@@@@@@@          ³
   ³  Rechnung  : D@@@@@@@@@@                                                     ³
   ³  Kst.stelle: T@@@@@@@@@@                                                     ³
   ³                                                                              ³
   ³  Kopftextbaustein :@@@@@@@@@@@@@@@@@@@@                                      ³
   ³  Fusstextbaustein :@@@@@@@@@@@@@@@@@@@@                                      ³
   ³  Platzhalter 1    :@@@@@@@@@@@@@@@@@@@@                                      ³
   ³                                                                              ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
   !R!FTMD13;FONT50255;EXIT;ğ[F1]=Hilfeğğ[Alt]+[F1]=Indexğğ[F2]=Suchenğğ[F10]=Men§ğğ[ESC]=EndeğğğğğğğğğğT02ğ!R!FTMD13;FONT50055;SLS.142;EXIT;



   Hilfe f§r: ¯Angebotserfassung®
   ------------------------------

   Angebotserfassung
                                                                       
   Ziel dieses Programms ist die  Verwaltung von Angeboten,            
   Kostenvoranschl¥gen und Mehrfachvorg¥ngen.                          
                                                                       
   KOPFERFASSUNG                                                       
                                                                       
   Geben Sie auf der 1. Bearbeitungsmaske die Eingaben zum Empf¥nger,  
   der Versandart, evtl. Kopf- und Fusstexte oder einer abweichenden   
   Lieferadresse an.                                                   
                                                                       
   POSITIONSERFASSUNG                                                  
                                                                       
   - Das Einlesen von Textbausteinen kann §ber die F2-Taste in (T)ext  
     und (K)ommentar-Positionen erfolgen.                              
                                                                       
     Der Unterschied zwischen den Positionsarten (T)ext und (K)ommentar
     besteht darin, da¨ Texte in einen weiteren Vorgang §bernommen     
     werden, Kommentare nicht.                                         
                                                                       
   - Sprung nach Menge je nach Angabe im Artikelstamm                  
                                                                       
   - Alternativpositionen                                              
     Im Unterschied zur Auftragsbearbeitung gibt es hier die M¦glich-  
     keit Alternativpositionen einzugeben, diese werden nicht berechnet
     und bei ¤bernahme in die Auftragsbearbeitung unterdr§ckt.         
                                                                       
                                                                       
   MEHRFACHVORG¢NGE                                                    
                                                                       
   Ist das Zusatzpaket "Mehrfachvorg¥nge" installiert, so haben Sie die
   M¦glichkeit, wiederholbare und neutrale Angebote zu erstellen.      
                                                                       
   Bei Anwahl dieser Position werden Ihnen die Felder 27, 28 und 29 zu-
   s¥tzlich eingeblendet.                                              
                                                                       
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                   II. Bereich: Auftrag... / 1.3
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;                                                                       

   Hilfe f§r: ¯Vorgang®
   --------------------

   Geben Sie hier den Vorgang an, den Sie bearbeiten m¦chten.
   
   Folgende M¦glichkeiten stehen Ihnen zur Verf§gung:
   
     F2  =  Auswahl
            - Angebot
            - Kostenvoranschlag
            - Mehrfachvorgang.
   
   Angebote u. Kostenvoranschl¥ge k¦nnen §ber F3 in Auftr¥ge und Vor-
            g¥nge im Programm <Einzelauftr¥ge> §bernommen werden und
            optional nach ¤bergabe gel¦scht werden.
   
   Mehrfachvorgang k¦nnen f§r bestimmte Kunden (Neutrale Vorg¥nge:
           Nein) oder f§r alle Kunden (Neutraler Vorgang: Ja) angelegt
            werden.
            Aus bestehenden Mehrfachvorg¥ngen k¦nnen §ber das
            Zusatzpaket <Mehrfachvorg¥nge> automatisch Auftr¥ge,
            Lieferungen, Rechnungen oder Direktrechnungen generi-
            ert werden.
            Diese stehen wie manuell erfa¨te Vorg¥nge zur weiteren
            Verarbeitung zur Verf§gung.
   
   

   Hilfe f§r: ¯Nummer®
   -------------------

   Geben Sie hier die gew¥hlte Vorgangsnummer ein.
   
   Folgende Auswahlm¦glichkeiten stehen Ihnen zur Verf§gung.
   
     F2        =  Suche nach vorhandenem Angebot
   
     F10       =  Neue Nummer zu gew¥hltem Vorgang
   
   Mit PFEIL OBEN / PFEIL UNTEN / ESC gelangen Sie wieder ins Feld
   "Vorgang".
   
   

   Hilfe f§r: ¯Empf¥nger®
   ----------------------

   Geben Sie hier die Nummer des Kunden an. Das Programm stellt Ihnen 5
   Stellen zur Verf§gung.                                              
                                                                       
   Folgende Auswahlm¦glichkeiten stehen Ihnen zur Verf§gung:           
                                                                       
      F2        =  Suche nach Kurzbezeichnung                          
                                                                       
      SHIFT+F2  =  Auswahl                                             
                   - Suche nach Bezeichnung                            
                   - Suche nach Nummer                                 
                   - Suche nach Ansprechpartner                        
                   - Suche nach Postleitzahl                           
                                                                       
      F10       =  neuer Kunde                                         
                                                                       
     - Falls die von Ihnen angegebene Kundennummer noch nicht im       
       Kundenstamm angelegt ist, erfolgt die Abfrage, ob der Kunde     
       angelegt werden soll, es wird automatisch in den <Kundenstamm>  
       zur Neuanlage verzweigt.                                        
                                                                       
     - Wenn Sie eine g§ltige Nummer eingeben (Kunde ist im Kundenstamm 
       vorhanden) springt das Programm in Feld 18.                     
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                   II. Bereich: Auftrag... / 1.4
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;                                                                       
       In die Felder 02 - 17 werden automatisch die Werte aus dem      
       Kundenstamm eingetragen.                                        
                                                                       
                                                                       

   Hilfe f§r: ¯Vertreter®
   ----------------------

   Hier wird der Vertreter gem¥¨ Ihrer Zuordnung im <Kundenstamm>
   vorgeschlagen.                                                      
                                                                       
   Sie k¦nnen eine ¢nderung vornehmen, die jedoch nur f§r diesen       
   Vorgang g§ltig ist und nicht im Kundenstamm ge¥ndert wird.          
                                                                       
   Der Vertreter mu¨ im <Vertreterstamm> angelegt sein.                
                                                                       
   F§r diesen Vertreter erfolgt die Provisionierung und die Abspeicher-
   ung der Statistik.                                                  
                                                                       
   In Feld 22 dieser Bildschirmmaske, wird die Kostenstelle, die Sie im
   <Vertreterstamm> zugeordnet haben, §bernommen.                      
                                                                       
   F2  =  Suche nach Vertreternummer.                                  
                                                                       
   Wird "999" f§r "Sammelvertreter" eingetragen, erfolgt die Ab-       
   speicherung der Statistik gem¥¨ Ihrer Festlegung im Programm        
   <Bearbeiten Mandant> Feld 08 (Seite 2/5).                           
                                                                       
   Die Vertreternummer dient zus¥tzlich als Selektionskriterium f§r    
   die Auswertung "Offene Auftr¥ge nach Kunde".                        
                                                                       
                                                                       

   Hilfe f§r: ¯Tour/Gebiet®
   ------------------------

   Dieses Feld enth¥lt die Nummer einer Tour oder eines Gebietes, die/
   das Sie dem Kunden zugeordnet haben.                                
                                                                       
   - Sie k¦nnen jedoch ¢nderungen vornehmen, die allerdings nur f§r    
     diesen Vorgang gelten und nicht im Kundenstamm gespeichert werden.
                                                                       
                                                                       

   Hilfe f§r: ¯Name 1®
   -------------------

   Dieses Feld enth¥lt den Namen des Kunden.
                                                                   
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   

   Hilfe f§r: ¯Preisgruppe®
   ------------------------

   Dieses Feld enth¥lt die Zuordnung f§r die Preisgruppe (Feld 15
   Kundenstamm). Die Preisgruppe bestimmt den Verkaufspreis (aus dem
   Artikel stamm) der dem Kunden in Rechnung gestellt werden soll.  
                                                                    
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen 
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.    
                                                                    
     F2  =  Auswahl aus den m¦glichen Preisgruppen                  
                                                                    
                                                                    

   Hilfe f§r: ¯Name 2®
   -------------------

   Dieses Feld enth¥lt einen Zusatz zum Kundennamen.
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                   II. Bereich: Auftrag... / 1.5
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;                                                                   
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   

   Hilfe f§r: ¯Rabattgruppe®
   -------------------------

   Dieses Feld enth¥lt die Nummer f§r eine Rabattgruppe.
                                                                       
   Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen      
   Vorgang gelten und nicht im Kundenstamm gespeichert werden.         
                                                                       
   Durch Zuordnung einer Nummer bestimmen Sie, ob dem Kunden ein Rabatt
   satz aus der Kunden/Artikelgruppen-Rabattmatrix (in Verbindung      
   mit Ihrem Eintrag im Artikelstamm Feld 30 - Rabattgruppe) zugeordnet
   werden soll.                                                        
                                                                       
   Sie haben die M¦glichkeit bis zu 8 Rabattgruppen in Verbindung mit  
   der Preisgruppe (Feld 17 Kundenstamm) zu 8 verschiedenen Artikel-   
   rabattgruppen anzulegen.                                            
   Ihr Eintrag von "0" bedeutet hier, da¨ dieser Kunde keinen Kunden/  
   Artikelgruppenrabatt bekommt.                                       
                                                                       
   Der Artikel mu¨ im Artikelstamm (Feld 33) als rabattierf¥hig ausge- 
   wiesen werden.                                                      
                                                                       
   Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen Vor- 
   gang gelten und nicht im Kundenstamm gespeichert werden.            
                                                                       
                                                                       

   Hilfe f§r: ¯Strasse/PLZ Ort®
   ----------------------------

   Diese Felder enthalten die vollst¥ndige Adresse des Kunden.
                                                                   
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   

   Hilfe f§r: ¯Zahlungskonditionen®
   --------------------------------

   Dieses Feld enth¥lt einen Zahlencode f§r die Zahlungskonditionen des
   Kunden.                                                             
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
     Dr§cken Sie die F2-Taste. Es ¦ffnet sich ein Fenster mit drei Ein-
     gabefeldern:                                                      
                                                                       
     - ??? Tage Skonto                                                 
     - mit ?,? Prozent                                                 
     - ??? Tage ohne Skonto.                                           
                                                                       
     1. Tragen Sie dort zun¥chst die Zahl der Tage ein, die der Kunde  
        Skonto erhalten soll. Das Programm stellt daf§r 3 Stellen      
        numerisch zur Verf§gung.                                       
                                                                       
     2. Tragen Sie den Skonto-Prozentsatz ein. Das Programm stellt eine
        Vor- und eine Nachkommastelle zur Verf§gung.                   
                                                                       
     3. Setzen Sie im letzten Feld das Zahlungsziel "rein netto ohne   
        Abzug" ein (Anzahl Tage). Das Programm stellt maximal 3 Stellen
        numerisch zur Verf§gung.                                       
                                                                       
     Sie k¦nnen die Verschl§sselung der Zahlungskonditionen auch direkt
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                   II. Bereich: Auftrag... / 1.6
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;     im Feld eingeben.                                                 
                                                                       
     !!! WICHTIG !!!  In diesem Fall m§ssen Sie auch die f§hrenden     
                      Nullen mit eingeben.                             
                                                                       
     Verschl§sselung: 008 25 030                                       
                       ³  ³   ÀÄÄÄÄ  30 Tage ohne Skonto               
                       ³  ³                                            
                       ³  ÀÄÄÄÄÄÄÄÄ  2,5 % Skonto                      
                       ³                                               
                       ÀÄÄÄÄÄÄÄÄÄÄÄ  8 Tage Skonto                     
                                                                       
                                                                       

   Hilfe f§r: ¯PLZ/Ort®
   --------------------

   Diese Felder enthalten die vollst¥ndige Adresse des Kunden.
                                                                   
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   
                                                                   

   Hilfe f§r: ¯Umsatzsteuerschl§ssel®
   ----------------------------------

   Dieses Feld enth¥lt einen Schl§ssel f§r die Umsatzsteuerberechnung.
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
     0  =  keine Umsatzsteuer                                          
           (= keine Berechnung der Umsatzsteuer, i.d.R. bei Auslands-  
           kunden)                                                     
                                                                       
        !!! WICHTIG !!!  Sie k¦nnen einem Kunden kein Fremdw¥hrungs-   
                         kennzeichen zuweisen, solange der Umsatz- bzw.
                         Vorsteuerschl§ssel nicht auf "0" gesetzt ist! 
                                                                       
     1  =  mit Umsatzsteuer                                            
           (= gesonderte Berechnung der Umsatzsteuer zus¥tzlich zu den 
           jeweiligen Artikelpreisen)                                  
                                                                       
     2  =  Bruttopreise                                                
           (= Umsatzsteuer ist bereits im Artikelpreis enthalten)      
                                                                       
           !!! WICHTIG !!!  Reservieren Sie in diesem Fall eine eigene 
                            Preisgruppe, da dieser Preis dann ja ein   
                            Bruttopreis (incl. Umsatzsteuer) im        
                            Gegensatz zu den Nettoverkaufspreisen      
                            (excl. Umsatzsteuer) ist.                  
                                                                       
     F2  =  Auswahl aus den m¦glichen Eingaben.                        
                                                                       
                                                                       

   Hilfe f§r: ¯Kurzbezeichnung®
   ----------------------------

   - Falls dieser Kunde bereits im Kundenstamm angelegt ist, dient
     dieses Feld zu Ihrer Information.                             
     Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   

   Hilfe f§r: ¯Rechnungskreis®
   ---------------------------

   Dieses Feld enth¥lt den Rechnungskreis, den Sie im <Kundenstamm>
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                   II. Bereich: Auftrag... / 1.7
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   festgelegt haben.                                                   
                                                                       
   -Sie k¦nnen ¢nderungen vornehmen, die nur f§r diesen Vorgang        
    gelten und nicht im Kundenstamm gespeichert werden.                
                                                                       
    Die Eingabe oder Auswahl (mit der F2-Taste) des Rechnungskreises   
    1 - 9 legt die entsprechenden Abrechnungsperioden fest. Bei Eingabe
    eines Kennzeichens erfolgt sp¥ter eine Auswahlm¦glichkeit bei der  
    <Stapelabrechnung> in den Feldern "Abrechnungskreis" von/bis".     
                                                                       
    Sie k¦nnen die Vergabe eines Sammelrechnungskennzeichens z.B. nach 
    zeitlichen Kriterien vornehmen.                                    
                                                                       
    Beispiel: 1 = w¦chentliche Berechnung                              
              2 = zweiw¦chentliche Berechnung                          
              3 = monatliche Berechnung                                
              usw.                                                     
                                                                       
                                                                       

   Hilfe f§r: ¯Rabattsatz®
   -----------------------

   Dieses Feld enth¥lt den prozentualen Rabattsatz des Kunden.
                                                                     
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen  
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.     
                                                                     
   Der hier eingetragene Rabatt wird von dem Gesamtrechnungsbetrag in
   Abzug gebracht.                                                   
                                                                     
                                                                     

   Hilfe f§r: ¯Datum®
   ------------------

   Geben Sie hier das Datum ein,
   an dem der Vorgang erfasst wurde.      
                                          
   Bitte geben Sie das Datum in der Form  
   TTMMJJ ein.                            
                                          
   Beispiel: Die Eingabe "120492" bedeutet
             12. April 1992.              
                                          
   Vorgeschlagen wird das aktuelle System-
   datum.                                 
                                          
                                          

   Hilfe f§r: ¯Provision®
   ----------------------

   Dieses Feld enth¥lt den prozentualen Provisionsanteil des
   Vertreters.                                                         
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
   - Wird hier eine Eingabe gemacht, so finden Ihre Angaben zum Pro-   
     visionssatz der einzelnen Artikel (Feld 06 Artikelstamm), sowie   
     beim jeweiligen Vertreter (Feld 02 Vertreterstamm) beim Gesamt-   
     rechnungsbetrag keine Ber§cksichtigung.                           
                                                                       
   - Bei Eingabe des Provisionsatzes 0.00" wird der im Artikel hinter- 
     legte Provisionssatz als Berechnungsgrundlage genommen, unabh¥ngig
     von dem im Vertreterstamm eingetragenen Provisionssatz.           
                                                                       
     Tragen Sie die Provision f§r diesen Vertreter in Prozenten ein.   
     Das Programm stellt 2 Vor- und 2 Nachkommastellen zur Verf§gung.  
                                                                       
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                   II. Bereich: Auftrag... / 1.8
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;                                                                       

   Hilfe f§r: ¯Mitarbeiter®
   ------------------------

   Geben Sie hier den Mitarbeiter ein,
   der den Vorgang bearbeitet.         
                                       
     F2  =  Suche nach Mitarbeiter.    
                                       
   Nach dem <Statistiklauf> werden im  
   <Mitarbeiterstamm> die dem jeweili- 
   gen Mitarbeiter zugeordneten Ums¥tze
   aktualisiert.                       
                                       
                                       

   Hilfe f§r: ¯Versandart®
   -----------------------

   In diesem Feld k¦nnen Sie die Versandart angeben.
                                                     
     F2  =  Auswahl aus den angelegten Versandarten  
                                                     
   Umfang und Inhalt dieser Auswahlliste richtet sich
   nach Ihren eigenen Einstellungen beim Anlegen m¦g-
   licher Versandarten. Dies k¦nnen Sie in der Auf-  
   tragsbearbeitung in den Grundlagen im Men§punkt   
   <Versandarten> tun.                               
                                                     
                                                     

   Hilfe f§r: ¯Sprachcode®
   -----------------------

   Dieses Feld enth¥lt die Sprache, in der der Schriftverkehr mit dem
   Kunden erfolgen soll.                                               
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
       F2  =  Auswahl aus den m¦glichen Fremdsprachen                  
                                                                       
     Die Auswahlwerte dieses Fensters richten sich nach Ihren Eingaben 
     in der "Finanzbuchhaltung" oder in der "Auftragsbearbeitung" in   
     den Grundlagen im Programm <Fremdw¥hrung/sprache>.                
                                                                       
   Beachten Sie bitte, da¨ bei Nutzung der Option "Fremdsprache" auch  
   ein entsprechendes Formular f§r die gew¥hlte Sprache existieren mu¨.
                                                                       
                                                                       

   Hilfe f§r: ¯Rechnung®
   ---------------------

   In diesem Feld k¦nnen Sie einen abweichenden Rechnungsempf¥nger
   bestimmen.                                                          
                                                                       
   Haben Sie im Kundenstamm bereits eine Festlegung getroffen, wird    
   hier die Kundennummer des abweichenden Rechnungsempf¥ngers ange-    
   zeigt.                                                              
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
   Bei der Bearbeitung einer Rechnung f§r einen Kunden mit abweichendem
   Rechnungsempf¥nger werden die Angaben des Kunden, an den die Rech-  
   nungsstellung erfolgen soll, im Anschriftenteil angezeigt.          
                                                                       
                                                                       

!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                   II. Bereich: Auftrag... / 1.9
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   Hilfe f§r: ¯Kostenstelle®
   -------------------------

   Die Kostenstelle wird automatisch vorgeschlagen, wenn Sie bei dem
   Vertreter im <Vertreterstamm> eine Zuordnung vorgenommen haben.  
                                                                    
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen 
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.    
                                                                    
     F2  =  Auswahl aus den bestehenden Kostenstellen.              
                                                                    
   Bei ¤bergabe in die Finanzbuchhaltung, werden die Erl¦se der     
   Fakturierung auf diese Kostenstelle verbucht.                    
                                                                    
   Neue Kostenstellen k¦nnen Sie in der "Finanzbuchhaltung" im      
   Programm <Kostenstellenstamm> erfassen.                          
                                                                    
                                                                    

   Hilfe f§r: ¯Kopftextbaustein®
   -----------------------------

   Hier haben Sie die M¦glichkeit einen Kopf-
   textbaustein f§r diesen Vorgang anzugeben.       
                                                    
      F2 =  Suche nach Textbausteinen               
                                                    
   Dieser Textbaustein wird beim Ausdruck im        
   Kopfteil der Formulare gedruckt.                 
                                                    
   Beachten Sie, da¨ Sie Platzhalter <{1} und {2}>  
   in Ihre Textbausteine einsetzen k¦nnen. In diese 
   Platzhalter wird der Text, den Sie in den Feldern
   25 und 26 eingetragen haben, gedruckt.           
                                                    
                                                    

   Hilfe f§r: ¯Fu¨textbaustein®
   ----------------------------

   Hier haben Sie die M¦glichkeit einen Fu¨-
   textbaustein f§r diesen Vorgang anzugeben.       
                                                    
      F2 =  Suche nach Textbausteinen               
                                                    
   Dieser Textbaustein wird beim Ausdruck im        
   Fu¨teil der Formulare gedruckt.                  
                                                    
   Beachten Sie, da¨ Sie Platzhalter <{1} und {2}>  
   in Ihre Textbausteine einsetzen k¦nnen. In diese 
   Platzhalter wird der Text, den Sie in den Feldern
   25 und 26 eingetragen haben, gedruckt.           
                                                    
                                                    

   Hilfe f§r: ¯Platzhalter 1®
   --------------------------

   Geben Sie hier den Inhalt f§r die Platz-
   halter {1} und {2} ein.                 
                                           
   Diese Platzhalter k¦nnen Sie bei der    
   Textbausteinanlage angeben.             
                                           
   Es stehen Ihnen jeweils 20 Stellen,     
   die Sie alpha-numerisch angeben k¦nnen, 
   f§r Ihre Eingabe zur Verf§gung.         
                                           
                                           

   Hilfe f§r: ¯Platzhalter 2®
   --------------------------

   Geben Sie hier den Inhalt f§r die Platz-
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.10
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   halter {1} und {2} ein.                 
                                           
   Diese Platzhalter k¦nnen Sie bei der    
   Textbausteinanlage angeben.             
                                           
   Es stehen Ihnen jeweils 20 Stellen,     
   die Sie alpha-numerisch angeben k¦nnen, 
   f§r Ihre Eingabe zur Verf§gung.         
                                           
                                           
!R!FTMD13;FONT50055;SLS.142;EXIT;
   !R!FTMD13;FONT50055;SLS.142;EXIT;Ein-/Ausgabefelder f§r: Bearbeiten Angebote (AUFM271)
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Ú(c) 1993 WINware ÄÄÄÄÄ WINware P.Mayer / A-1040 Wien ÄÄÄÄÄ Datum 01.12.93 (01)¿
   À!R!FTMD13;FONT50255;EXIT;ğğF-TastenğğOptionenğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğF1=Hilfeğğğğ!R!FTMD13;FONT50055;SLS.142;EXIT;Ù
   ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄBearbeiten Angebote - 2/2Ä¿
   ³                                                                              ³
   ³  Vorgang: Angebot         Nummer: @@@@@@@@@                                  ³
   ³                                                                              ³
   ³                                                                              ³
   ³  Artikel              Hrst. SS   Menge KW LO Rab.%    E-Preis PE    G-Preis  ³
   ³ @ @@@@@@@@@@@@@@@     @@@@@ @@   @@@@@ @@ @@ @@@@@@@  @@@@@@@ @@    @@@@@ @  ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                  Gesamtbetrag   ^^^^^^^^^^   ³
   ³                                                                              ³
   ³ Bestand                                                                      ³
   ³    ^^^^^^^^^^^                                                               ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
   !R!FTMD13;FONT50255;EXIT;ğ[F1]=Hilfeğğ[Alt]+[F1]=Indexğğ[F2]=Suchenğğ[F10]=Men§ğğ[ESC]=EndeğğğğğğğğğğT02ğ!R!FTMD13;FONT50055;SLS.142;EXIT;



   Hilfe f§r: ¯Angebotserfassung®
   ------------------------------

   Angebotserfassung
                                                                       
   Ziel dieses Programms ist die  Verwaltung von Angeboten,            
   Kostenvoranschl¥gen und Mehrfachvorg¥ngen.                          
                                                                       
   KOPFERFASSUNG                                                       
                                                                       
   Geben Sie auf der 1. Bearbeitungsmaske die Eingaben zum Empf¥nger,  
   der Versandart, evtl. Kopf- und Fusstexte oder einer abweichenden   
   Lieferadresse an.                                                   
                                                                       
   POSITIONSERFASSUNG                                                  
                                                                       
   - Das Einlesen von Textbausteinen kann §ber die F2-Taste in (T)ext  
     und (K)ommentar-Positionen erfolgen.                              
                                                                       
     Der Unterschied zwischen den Positionsarten (T)ext und (K)ommentar
     besteht darin, da¨ Texte in einen weiteren Vorgang §bernommen     
     werden, Kommentare nicht.                                         
                                                                       
   - Sprung nach Menge je nach Angabe im Artikelstamm                  
                                                                       
   - Alternativpositionen                                              
     Im Unterschied zur Auftragsbearbeitung gibt es hier die M¦glich-  
     keit Alternativpositionen einzugeben, diese werden nicht berechnet
     und bei ¤bernahme in die Auftragsbearbeitung unterdr§ckt.         
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.11
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;                                                                       
                                                                       
   MEHRFACHVORG¢NGE                                                    
                                                                       
   Ist das Zusatzpaket "Mehrfachvorg¥nge" installiert, so haben Sie die
   M¦glichkeit, wiederholbare und neutrale Angebote zu erstellen.      
                                                                       
   Bei Anwahl dieser Position werden Ihnen die Felder 27, 28 und 29 zu-
   s¥tzlich eingeblendet.                                              
                                                                       
                                                                       

   Hilfe f§r: 
   -----------

   WINware 1.Feld = EingabeFeld Wirklich = nur Ausgabefeld

   Hilfe f§r: ¯Positionsart®
   -------------------------

   Hier k¦nnen Sie die Positionsart festlegen :
   
        A = Artikel
        S = St§ckliste
        N = Seriennummer
        L = Langtext
        T = Text (mit ¤bernahme)
        K = Text (ohne ¤bernahme)
        Z = Zwischensumme
        F = Fester Seitenumbruch
   
   

   Hilfe f§r: ¯Artikelnummer®
   --------------------------

   Bezeichnung 1 + Bezeichnung 2 des Artikels / der St§ckliste
   
   Wenn Sie die Positionsart "A" gew¥hlt haben, geben Sie bitte hier
   die Artikelnummer ein, oder w¥hlen §ber die F2-Auswahl den
   gew§nschten Artikel.
   
   Es wird die Bezeichnung 1+2 des Artikels oder der St§ckliste
   angezeigt, die in den Stammdaten eingetragen ist.
   
   Mit der Taste " PFEIL OBEN" gelangen Sie wieder ins Feld "Positions-
   art".
   
   

   Hilfe f§r: ¯Angebotserfassung®
   ------------------------------

   Angebotserfassung
                                                                       
   Ziel dieses Programms ist die  Verwaltung von Angeboten,            
   Kostenvoranschl¥gen und Mehrfachvorg¥ngen.                          
                                                                       
   KOPFERFASSUNG                                                       
                                                                       
   Geben Sie auf der 1. Bearbeitungsmaske die Eingaben zum Empf¥nger,  
   der Versandart, evtl. Kopf- und Fusstexte oder einer abweichenden   
   Lieferadresse an.                                                   
                                                                       
   POSITIONSERFASSUNG                                                  
                                                                       
   - Das Einlesen von Textbausteinen kann §ber die F2-Taste in (T)ext  
     und (K)ommentar-Positionen erfolgen.                              
                                                                       
     Der Unterschied zwischen den Positionsarten (T)ext und (K)ommentar
     besteht darin, da¨ Texte in einen weiteren Vorgang §bernommen     
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.12
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;     werden, Kommentare nicht.                                         
                                                                       
   - Sprung nach Menge je nach Angabe im Artikelstamm                  
                                                                       
   - Alternativpositionen                                              
     Im Unterschied zur Auftragsbearbeitung gibt es hier die M¦glich-  
     keit Alternativpositionen einzugeben, diese werden nicht berechnet
     und bei ¤bernahme in die Auftragsbearbeitung unterdr§ckt.         
                                                                       
                                                                       
   MEHRFACHVORG¢NGE                                                    
                                                                       
   Ist das Zusatzpaket "Mehrfachvorg¥nge" installiert, so haben Sie die
   M¦glichkeit, wiederholbare und neutrale Angebote zu erstellen.      
                                                                       
   Bei Anwahl dieser Position werden Ihnen die Felder 27, 28 und 29 zu-
   s¥tzlich eingeblendet.                                              
                                                                       
                                                                       
   

   Hilfe f§r: ¯Menge®
   ------------------

   Geben Sie hier die Menge dieser Artikel/St§cklistenposition ein.
   
   Die Menge dient zur Ermittlung des Gesamtpreises (G-Preis).
   
   Bei Artikel mit Preiserrechnung > 0 Feld 12 im <Artikel-
   stamm> springt das Programm automatisch in die Fu¨zeile zur
   Eingabe der Anzahl und der Dimensionen. Das Ergebnis wird dann
   automatisch in diesem Feld §bernommen.
   
   Falls Sie im Feld 05 "Mengenformat" <Artikelstamm> Nachkomma-
   stellen angegeben haben, beachten Sie dabei bitte, da¨ auf die
   letzte Nachkommastelle vom Programm die Rundung erfolgt; dies
   ist besonders bei der Preisberechnung von Artikeln mit Dimensionen
   von Bedeutung.
   
   Beispiele:
   
   1) Artikel mit 3 Nachkommastellen im Mengenformat
      Anz  x  L¥nge  x  Breite  x  H¦he    Menge      E-Preis   G-Preis
       1       0,5       0,5       0,5     0,125      100,00     12,50
   
   2) Artikel mit 2 Nachkommastellen im Mengenformat
      Anz  x  L¥nge  x  Breite  x  H¦he    Menge      E-Preis   G-Preis
       1       0,5       0,5       0,5     0,13       100,00     13,00
   
   PFEIL OBEN   =  R§cksprung ins Feld "Positionsart"
   PFEIL UNTEN  =  Sprung ins Feld "Positionsabschlu¨"
   
   

   Hilfe f§r: ¯Lieferwoche®
   ------------------------

   Sie k¦nnen hier, manuell oder mit F2, die Lieferwoche f§r die Sie
   die Lieferung eingetragen haben, w¥hlen.                            
                                                                       
   Die F2 Funktion erm¦glicht Ihnen eine Einsicht §ber Auftragsbestand,
   Bestellmenge und verf§gbare Menge, aus der 52 Wochendisposition des 
   Artikels.                                                           
                                                                       
                                                                       
   

   Hilfe f§r: ¯Lagerorte®
   ----------------------

   Hier k¦nnen Sie entscheiden, von welchem Lagerort Ihr Artikel
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.13
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   abgebucht werden soll.
   
   Sie k¦nnen sich §ber die F2 Funktion Ihre 14 Lagerorte anzeigen
   lassen.
   
   

   Hilfe f§r: ¯Rabatt®
   -------------------

   Hier wird evtl. §ber die Preisfindung ermittelter Rabatt-Prozentsatz
   automatisch vom Programm vorgeschlagen.
   
   ¤ber die Option "Preisnachweis" erfolgt die Anzeige wie dieser
   Preis ermittelt wurde.
   
   

   Hilfe f§r: ¯Angebotserfassung®
   ------------------------------

   Angebotserfassung
                                                                       
   Ziel dieses Programms ist die  Verwaltung von Angeboten,            
   Kostenvoranschl¥gen und Mehrfachvorg¥ngen.                          
                                                                       
   KOPFERFASSUNG                                                       
                                                                       
   Geben Sie auf der 1. Bearbeitungsmaske die Eingaben zum Empf¥nger,  
   der Versandart, evtl. Kopf- und Fusstexte oder einer abweichenden   
   Lieferadresse an.                                                   
                                                                       
   POSITIONSERFASSUNG                                                  
                                                                       
   - Das Einlesen von Textbausteinen kann §ber die F2-Taste in (T)ext  
     und (K)ommentar-Positionen erfolgen.                              
                                                                       
     Der Unterschied zwischen den Positionsarten (T)ext und (K)ommentar
     besteht darin, da¨ Texte in einen weiteren Vorgang §bernommen     
     werden, Kommentare nicht.                                         
                                                                       
   - Sprung nach Menge je nach Angabe im Artikelstamm                  
                                                                       
   - Alternativpositionen                                              
     Im Unterschied zur Auftragsbearbeitung gibt es hier die M¦glich-  
     keit Alternativpositionen einzugeben, diese werden nicht berechnet
     und bei ¤bernahme in die Auftragsbearbeitung unterdr§ckt.         
                                                                       
                                                                       
   MEHRFACHVORG¢NGE                                                    
                                                                       
   Ist das Zusatzpaket "Mehrfachvorg¥nge" installiert, so haben Sie die
   M¦glichkeit, wiederholbare und neutrale Angebote zu erstellen.      
                                                                       
   Bei Anwahl dieser Position werden Ihnen die Felder 27, 28 und 29 zu-
   s¥tzlich eingeblendet.                                              
                                                                       
                                                                       
   
   ---------------------------------------------------


!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.14
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;!R!FTMD13;FONT50080;SLS.122;EXIT;
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Men§fenster ¯Hauptmen§® / Auftrag... (AUF-001):Auftrag
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50080;SLS.122;EXIT;
   ÚÄÄÄÄÄÄÄÄÄÄÄÄ¿             
   ³ Auftrag... ³                ... Bearbeiten und drucken v. Auftr¥gen, Rechnungen u. Gutschriften.
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄ¿
   ³ Angebote/Rechnungen...  ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Auftragseingangsbuch    ³
   ³ Rechnungsausgangsbuch   ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Statistiklauf           ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
!R!FTMD13;FONT50055;SLS.142;EXIT;

!R!FTMD13;FONT50055;SLS.142;EXIT;
   !R!FTMD13;FONT50055;SLS.142;EXIT;Ein-/Ausgabefelder f§r: Bearbeiten Auftr¥ge Rechnungen (AUFM200)
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Ú(c) 1993 WINware ÄÄÄÄÄ WINware P.Mayer / A-1040 Wien ÄÄÄÄÄ Datum 01.12.93 (01)¿
   À!R!FTMD13;FONT50255;EXIT;ğğF-TastenğğOptionenğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğF1=Hilfeğğğğ!R!FTMD13;FONT50055;SLS.142;EXIT;Ù
   ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄBearbeiten Auftr¥ge Rechnungen - 1/1Ä¿
   ³  Vorgang   :@@@@@@@@@@@@                   Nummer    :@@@@@@@@@@@@           ³
   ³                                                                              ³
   ³  Empf¥nger : D@@@@@@@@@@                   Vertreter       :@@@@@@@@@@@@@@   ³
   ³                                            Tour/Gebiet     :@@@@@@@@@@@@@@   ³
   ³  Name 1    :@@@@@@@@@@@@                   Preisgruppe     :@@@@@@@@@@@@@@   ³
   ³  Name 2    :@@@@@@@@@@@@                   Rabattgruppe    :@@@(0-8)         ³
   ³  Strasse   :@@@@@@@@@@@@                   Zahlungskond.   :@@@@@@@          ³
   ³  PLZ Ort   :@@@@@@@@@@@@                   USt.schl§ssel   :@@@@@@@          ³
   ³  Kurzbez.  :@@@@@@@@@@@@                   Rechnungskreis  :@@@(0-9)         ³
   ³                                            Rabattsatz      :@@@@@@@%         ³
   ³  Datum     :@@@@@@@@@@@@                   Provision       :@@@@@@@%         ³
   ³  Bearbeiter:@@@@@@@@@@@@                   W¥hrung         :@@@@@@@          ³
   ³  Versand   :@@@@@@@@@@@@                   Sprachcode      :@@@@@@@          ³
   ³  Rechnung  : D@@@@@@@@@@                                                     ³
   ³  Kst.stelle: T@@@@@@@@@@                                                     ³
   ³                                                                              ³
   ³  Kopftextbaustein :@@@@@@@@@@@@@@@@@@@@                                      ³
   ³  Fusstextbaustein :@@@@@@@@@@@@@@@@@@@@                                      ³
   ³  Platzhalter 1    :@@@@@@@@@@@@@@@@@@@@                                      ³
   ³                                                                              ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
   !R!FTMD13;FONT50255;EXIT;ğ[F1]=Hilfeğğ[Alt]+[F1]=Indexğğ[F2]=Suchenğğ[F10]=Men§ğğ[ESC]=EndeğğğğğğğğğğT02ğ!R!FTMD13;FONT50055;SLS.142;EXIT;



   Hilfe f§r: ¯Angebotserfassung®
   ------------------------------

   Angebotserfassung
                                                                       
   Ziel dieses Programms ist die  Verwaltung von Angeboten,            
   Kostenvoranschl¥gen und Mehrfachvorg¥ngen.                          
                                                                       
   KOPFERFASSUNG                                                       
                                                                       
   Geben Sie auf der 1. Bearbeitungsmaske die Eingaben zum Empf¥nger,  
   der Versandart, evtl. Kopf- und Fusstexte oder einer abweichenden   
   Lieferadresse an.                                                   
                                                                       
   POSITIONSERFASSUNG                                                  
                                                                       
   - Das Einlesen von Textbausteinen kann §ber die F2-Taste in (T)ext  
     und (K)ommentar-Positionen erfolgen.                              
                                                                       
     Der Unterschied zwischen den Positionsarten (T)ext und (K)ommentar
     besteht darin, da¨ Texte in einen weiteren Vorgang §bernommen     
     werden, Kommentare nicht.                                         
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.15
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;                                                                       
   - Sprung nach Menge je nach Angabe im Artikelstamm                  
                                                                       
   - Alternativpositionen                                              
     Im Unterschied zur Auftragsbearbeitung gibt es hier die M¦glich-  
     keit Alternativpositionen einzugeben, diese werden nicht berechnet
     und bei ¤bernahme in die Auftragsbearbeitung unterdr§ckt.         
                                                                       
                                                                       
   MEHRFACHVORG¢NGE                                                    
                                                                       
   Ist das Zusatzpaket "Mehrfachvorg¥nge" installiert, so haben Sie die
   M¦glichkeit, wiederholbare und neutrale Angebote zu erstellen.      
                                                                       
   Bei Anwahl dieser Position werden Ihnen die Felder 27, 28 und 29 zu-
   s¥tzlich eingeblendet.                                              
                                                                       
                                                                       

   Hilfe f§r: ¯Vorgang®
   --------------------

   Geben Sie hier den Vorgang an, den Sie bearbeiten m¦chten.
   
   Folgende M¦glichkeiten stehen Ihnen zur Verf§gung:
   
     F2  =  Auswahl
            - Angebot
            - Kostenvoranschlag
            - Mehrfachvorgang.
   
   Angebote u. Kostenvoranschl¥ge k¦nnen §ber F3 in Auftr¥ge und Vor-
            g¥nge im Programm <Einzelauftr¥ge> §bernommen werden und
            optional nach ¤bergabe gel¦scht werden.
   
   Mehrfachvorgang k¦nnen f§r bestimmte Kunden (Neutrale Vorg¥nge:
           Nein) oder f§r alle Kunden (Neutraler Vorgang: Ja) angelegt
            werden.
            Aus bestehenden Mehrfachvorg¥ngen k¦nnen §ber das
            Zusatzpaket <Mehrfachvorg¥nge> automatisch Auftr¥ge,
            Lieferungen, Rechnungen oder Direktrechnungen generi-
            ert werden.
            Diese stehen wie manuell erfa¨te Vorg¥nge zur weiteren
            Verarbeitung zur Verf§gung.
   
   

   Hilfe f§r: ¯Nummer®
   -------------------

   Geben Sie hier die gew¥hlte Vorgangsnummer ein.
   
   Folgende Auswahlm¦glichkeiten stehen Ihnen zur Verf§gung.
   
     F2        =  Suche nach vorhandenem Angebot
   
     F10       =  Neue Nummer zu gew¥hltem Vorgang
   
   Mit PFEIL OBEN / PFEIL UNTEN / ESC gelangen Sie wieder ins Feld
   "Vorgang".
   
   

   Hilfe f§r: ¯Empf¥nger®
   ----------------------

   Geben Sie hier die Nummer des Kunden an. Das Programm stellt Ihnen 5
   Stellen zur Verf§gung.                                              
                                                                       
   Folgende Auswahlm¦glichkeiten stehen Ihnen zur Verf§gung:           
                                                                       
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.16
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;      F2        =  Suche nach Kurzbezeichnung                          
                                                                       
      SHIFT+F2  =  Auswahl                                             
                   - Suche nach Bezeichnung                            
                   - Suche nach Nummer                                 
                   - Suche nach Ansprechpartner                        
                   - Suche nach Postleitzahl                           
                                                                       
      F10       =  neuer Kunde                                         
                                                                       
     - Falls die von Ihnen angegebene Kundennummer noch nicht im       
       Kundenstamm angelegt ist, erfolgt die Abfrage, ob der Kunde     
       angelegt werden soll, es wird automatisch in den <Kundenstamm>  
       zur Neuanlage verzweigt.                                        
                                                                       
     - Wenn Sie eine g§ltige Nummer eingeben (Kunde ist im Kundenstamm 
       vorhanden) springt das Programm in Feld 18.                     
                                                                       
       In die Felder 02 - 17 werden automatisch die Werte aus dem      
       Kundenstamm eingetragen.                                        
                                                                       
                                                                       

   Hilfe f§r: ¯Vertreter®
   ----------------------

   Hier wird der Vertreter gem¥¨ Ihrer Zuordnung im <Kundenstamm>
   vorgeschlagen.                                                      
                                                                       
   Sie k¦nnen eine ¢nderung vornehmen, die jedoch nur f§r diesen       
   Vorgang g§ltig ist und nicht im Kundenstamm ge¥ndert wird.          
                                                                       
   Der Vertreter mu¨ im <Vertreterstamm> angelegt sein.                
                                                                       
   F§r diesen Vertreter erfolgt die Provisionierung und die Abspeicher-
   ung der Statistik.                                                  
                                                                       
   In Feld 22 dieser Bildschirmmaske, wird die Kostenstelle, die Sie im
   <Vertreterstamm> zugeordnet haben, §bernommen.                      
                                                                       
   F2  =  Suche nach Vertreternummer.                                  
                                                                       
   Wird "999" f§r "Sammelvertreter" eingetragen, erfolgt die Ab-       
   speicherung der Statistik gem¥¨ Ihrer Festlegung im Programm        
   <Bearbeiten Mandant> Feld 08 (Seite 2/5).                           
                                                                       
   Die Vertreternummer dient zus¥tzlich als Selektionskriterium f§r    
   die Auswertung "Offene Auftr¥ge nach Kunde".                        
                                                                       
                                                                       

   Hilfe f§r: ¯Tour/Gebiet®
   ------------------------

   Dieses Feld enth¥lt die Nummer einer Tour oder eines Gebietes, die/
   das Sie dem Kunden zugeordnet haben.                                
                                                                       
   - Sie k¦nnen jedoch ¢nderungen vornehmen, die allerdings nur f§r    
     diesen Vorgang gelten und nicht im Kundenstamm gespeichert werden.
                                                                       
                                                                       

   Hilfe f§r: ¯Name 1®
   -------------------

   Dieses Feld enth¥lt den Namen des Kunden.
                                                                   
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.17
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;
   Hilfe f§r: ¯Preisgruppe®
   ------------------------

   Dieses Feld enth¥lt die Zuordnung f§r die Preisgruppe (Feld 15
   Kundenstamm). Die Preisgruppe bestimmt den Verkaufspreis (aus dem
   Artikel stamm) der dem Kunden in Rechnung gestellt werden soll.  
                                                                    
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen 
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.    
                                                                    
     F2  =  Auswahl aus den m¦glichen Preisgruppen                  
                                                                    
                                                                    

   Hilfe f§r: ¯Name 2®
   -------------------

   Dieses Feld enth¥lt einen Zusatz zum Kundennamen.
                                                                   
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   

   Hilfe f§r: ¯Rabattgruppe®
   -------------------------

   Dieses Feld enth¥lt die Nummer f§r eine Rabattgruppe.
                                                                       
   Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen      
   Vorgang gelten und nicht im Kundenstamm gespeichert werden.         
                                                                       
   Durch Zuordnung einer Nummer bestimmen Sie, ob dem Kunden ein Rabatt
   satz aus der Kunden/Artikelgruppen-Rabattmatrix (in Verbindung      
   mit Ihrem Eintrag im Artikelstamm Feld 30 - Rabattgruppe) zugeordnet
   werden soll.                                                        
                                                                       
   Sie haben die M¦glichkeit bis zu 8 Rabattgruppen in Verbindung mit  
   der Preisgruppe (Feld 17 Kundenstamm) zu 8 verschiedenen Artikel-   
   rabattgruppen anzulegen.                                            
   Ihr Eintrag von "0" bedeutet hier, da¨ dieser Kunde keinen Kunden/  
   Artikelgruppenrabatt bekommt.                                       
                                                                       
   Der Artikel mu¨ im Artikelstamm (Feld 33) als rabattierf¥hig ausge- 
   wiesen werden.                                                      
                                                                       
   Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen Vor- 
   gang gelten und nicht im Kundenstamm gespeichert werden.            
                                                                       
                                                                       

   Hilfe f§r: ¯Strasse/PLZ Ort®
   ----------------------------

   Diese Felder enthalten die vollst¥ndige Adresse des Kunden.
                                                                   
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   

   Hilfe f§r: ¯Zahlungskonditionen®
   --------------------------------

   Dieses Feld enth¥lt einen Zahlencode f§r die Zahlungskonditionen des
   Kunden.                                                             
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.18
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;     Dr§cken Sie die F2-Taste. Es ¦ffnet sich ein Fenster mit drei Ein-
     gabefeldern:                                                      
                                                                       
     - ??? Tage Skonto                                                 
     - mit ?,? Prozent                                                 
     - ??? Tage ohne Skonto.                                           
                                                                       
     1. Tragen Sie dort zun¥chst die Zahl der Tage ein, die der Kunde  
        Skonto erhalten soll. Das Programm stellt daf§r 3 Stellen      
        numerisch zur Verf§gung.                                       
                                                                       
     2. Tragen Sie den Skonto-Prozentsatz ein. Das Programm stellt eine
        Vor- und eine Nachkommastelle zur Verf§gung.                   
                                                                       
     3. Setzen Sie im letzten Feld das Zahlungsziel "rein netto ohne   
        Abzug" ein (Anzahl Tage). Das Programm stellt maximal 3 Stellen
        numerisch zur Verf§gung.                                       
                                                                       
     Sie k¦nnen die Verschl§sselung der Zahlungskonditionen auch direkt
     im Feld eingeben.                                                 
                                                                       
     !!! WICHTIG !!!  In diesem Fall m§ssen Sie auch die f§hrenden     
                      Nullen mit eingeben.                             
                                                                       
     Verschl§sselung: 008 25 030                                       
                       ³  ³   ÀÄÄÄÄ  30 Tage ohne Skonto               
                       ³  ³                                            
                       ³  ÀÄÄÄÄÄÄÄÄ  2,5 % Skonto                      
                       ³                                               
                       ÀÄÄÄÄÄÄÄÄÄÄÄ  8 Tage Skonto                     
                                                                       
                                                                       

   Hilfe f§r: ¯PLZ/Ort®
   --------------------

   Diese Felder enthalten die vollst¥ndige Adresse des Kunden.
                                                                   
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   
                                                                   

   Hilfe f§r: ¯Umsatzsteuerschl§ssel®
   ----------------------------------

   Dieses Feld enth¥lt einen Schl§ssel f§r die Umsatzsteuerberechnung.
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
     0  =  keine Umsatzsteuer                                          
           (= keine Berechnung der Umsatzsteuer, i.d.R. bei Auslands-  
           kunden)                                                     
                                                                       
        !!! WICHTIG !!!  Sie k¦nnen einem Kunden kein Fremdw¥hrungs-   
                         kennzeichen zuweisen, solange der Umsatz- bzw.
                         Vorsteuerschl§ssel nicht auf "0" gesetzt ist! 
                                                                       
     1  =  mit Umsatzsteuer                                            
           (= gesonderte Berechnung der Umsatzsteuer zus¥tzlich zu den 
           jeweiligen Artikelpreisen)                                  
                                                                       
     2  =  Bruttopreise                                                
           (= Umsatzsteuer ist bereits im Artikelpreis enthalten)      
                                                                       
           !!! WICHTIG !!!  Reservieren Sie in diesem Fall eine eigene 
                            Preisgruppe, da dieser Preis dann ja ein   
                            Bruttopreis (incl. Umsatzsteuer) im        
                            Gegensatz zu den Nettoverkaufspreisen      
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.19
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;                            (excl. Umsatzsteuer) ist.                  
                                                                       
     F2  =  Auswahl aus den m¦glichen Eingaben.                        
                                                                       
                                                                       

   Hilfe f§r: ¯Kurzbezeichnung®
   ----------------------------

   - Falls dieser Kunde bereits im Kundenstamm angelegt ist, dient
     dieses Feld zu Ihrer Information.                             
     Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   

   Hilfe f§r: ¯Rechnungskreis®
   ---------------------------

   Dieses Feld enth¥lt den Rechnungskreis, den Sie im <Kundenstamm>
   festgelegt haben.                                                   
                                                                       
   -Sie k¦nnen ¢nderungen vornehmen, die nur f§r diesen Vorgang        
    gelten und nicht im Kundenstamm gespeichert werden.                
                                                                       
    Die Eingabe oder Auswahl (mit der F2-Taste) des Rechnungskreises   
    1 - 9 legt die entsprechenden Abrechnungsperioden fest. Bei Eingabe
    eines Kennzeichens erfolgt sp¥ter eine Auswahlm¦glichkeit bei der  
    <Stapelabrechnung> in den Feldern "Abrechnungskreis" von/bis".     
                                                                       
    Sie k¦nnen die Vergabe eines Sammelrechnungskennzeichens z.B. nach 
    zeitlichen Kriterien vornehmen.                                    
                                                                       
    Beispiel: 1 = w¦chentliche Berechnung                              
              2 = zweiw¦chentliche Berechnung                          
              3 = monatliche Berechnung                                
              usw.                                                     
                                                                       
                                                                       

   Hilfe f§r: ¯Rabattsatz®
   -----------------------

   Dieses Feld enth¥lt den prozentualen Rabattsatz des Kunden.
                                                                     
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen  
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.     
                                                                     
   Der hier eingetragene Rabatt wird von dem Gesamtrechnungsbetrag in
   Abzug gebracht.                                                   
                                                                     
                                                                     

   Hilfe f§r: ¯Datum®
   ------------------

   Geben Sie hier das Datum ein,
   an dem der Vorgang erfasst wurde.      
                                          
   Bitte geben Sie das Datum in der Form  
   TTMMJJ ein.                            
                                          
   Beispiel: Die Eingabe "120492" bedeutet
             12. April 1992.              
                                          
   Vorgeschlagen wird das aktuelle System-
   datum.                                 
                                          
                                          

   Hilfe f§r: ¯Provision®
   ----------------------

   Dieses Feld enth¥lt den prozentualen Provisionsanteil des
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.20
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   Vertreters.                                                         
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
   - Wird hier eine Eingabe gemacht, so finden Ihre Angaben zum Pro-   
     visionssatz der einzelnen Artikel (Feld 06 Artikelstamm), sowie   
     beim jeweiligen Vertreter (Feld 02 Vertreterstamm) beim Gesamt-   
     rechnungsbetrag keine Ber§cksichtigung.                           
                                                                       
   - Bei Eingabe des Provisionsatzes 0.00" wird der im Artikel hinter- 
     legte Provisionssatz als Berechnungsgrundlage genommen, unabh¥ngig
     von dem im Vertreterstamm eingetragenen Provisionssatz.           
                                                                       
     Tragen Sie die Provision f§r diesen Vertreter in Prozenten ein.   
     Das Programm stellt 2 Vor- und 2 Nachkommastellen zur Verf§gung.  
                                                                       
                                                                       

   Hilfe f§r: ¯Mitarbeiter®
   ------------------------

   Geben Sie hier den Mitarbeiter ein,
   der den Vorgang bearbeitet.         
                                       
     F2  =  Suche nach Mitarbeiter.    
                                       
   Nach dem <Statistiklauf> werden im  
   <Mitarbeiterstamm> die dem jeweili- 
   gen Mitarbeiter zugeordneten Ums¥tze
   aktualisiert.                       
                                       
                                       

   Hilfe f§r: ¯Versandart®
   -----------------------

   In diesem Feld k¦nnen Sie die Versandart angeben.
                                                     
     F2  =  Auswahl aus den angelegten Versandarten  
                                                     
   Umfang und Inhalt dieser Auswahlliste richtet sich
   nach Ihren eigenen Einstellungen beim Anlegen m¦g-
   licher Versandarten. Dies k¦nnen Sie in der Auf-  
   tragsbearbeitung in den Grundlagen im Men§punkt   
   <Versandarten> tun.                               
                                                     
                                                     

   Hilfe f§r: ¯Sprachcode®
   -----------------------

   Dieses Feld enth¥lt die Sprache, in der der Schriftverkehr mit dem
   Kunden erfolgen soll.                                               
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
       F2  =  Auswahl aus den m¦glichen Fremdsprachen                  
                                                                       
     Die Auswahlwerte dieses Fensters richten sich nach Ihren Eingaben 
     in der "Finanzbuchhaltung" oder in der "Auftragsbearbeitung" in   
     den Grundlagen im Programm <Fremdw¥hrung/sprache>.                
                                                                       
   Beachten Sie bitte, da¨ bei Nutzung der Option "Fremdsprache" auch  
   ein entsprechendes Formular f§r die gew¥hlte Sprache existieren mu¨.
                                                                       
                                                                       

   Hilfe f§r: ¯Rechnung®
   ---------------------

   In diesem Feld k¦nnen Sie einen abweichenden Rechnungsempf¥nger
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.21
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   bestimmen.                                                          
                                                                       
   Haben Sie im Kundenstamm bereits eine Festlegung getroffen, wird    
   hier die Kundennummer des abweichenden Rechnungsempf¥ngers ange-    
   zeigt.                                                              
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
   Bei der Bearbeitung einer Rechnung f§r einen Kunden mit abweichendem
   Rechnungsempf¥nger werden die Angaben des Kunden, an den die Rech-  
   nungsstellung erfolgen soll, im Anschriftenteil angezeigt.          
                                                                       
                                                                       

   Hilfe f§r: ¯Kostenstelle®
   -------------------------

   Die Kostenstelle wird automatisch vorgeschlagen, wenn Sie bei dem
   Vertreter im <Vertreterstamm> eine Zuordnung vorgenommen haben.  
                                                                    
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen 
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.    
                                                                    
     F2  =  Auswahl aus den bestehenden Kostenstellen.              
                                                                    
   Bei ¤bergabe in die Finanzbuchhaltung, werden die Erl¦se der     
   Fakturierung auf diese Kostenstelle verbucht.                    
                                                                    
   Neue Kostenstellen k¦nnen Sie in der "Finanzbuchhaltung" im      
   Programm <Kostenstellenstamm> erfassen.                          
                                                                    
                                                                    

   Hilfe f§r: ¯Kopftextbaustein®
   -----------------------------

   Hier haben Sie die M¦glichkeit einen Kopf-
   textbaustein f§r diesen Vorgang anzugeben.       
                                                    
      F2 =  Suche nach Textbausteinen               
                                                    
   Dieser Textbaustein wird beim Ausdruck im        
   Kopfteil der Formulare gedruckt.                 
                                                    
   Beachten Sie, da¨ Sie Platzhalter <{1} und {2}>  
   in Ihre Textbausteine einsetzen k¦nnen. In diese 
   Platzhalter wird der Text, den Sie in den Feldern
   25 und 26 eingetragen haben, gedruckt.           
                                                    
                                                    

   Hilfe f§r: ¯Fu¨textbaustein®
   ----------------------------

   Hier haben Sie die M¦glichkeit einen Fu¨-
   textbaustein f§r diesen Vorgang anzugeben.       
                                                    
      F2 =  Suche nach Textbausteinen               
                                                    
   Dieser Textbaustein wird beim Ausdruck im        
   Fu¨teil der Formulare gedruckt.                  
                                                    
   Beachten Sie, da¨ Sie Platzhalter <{1} und {2}>  
   in Ihre Textbausteine einsetzen k¦nnen. In diese 
   Platzhalter wird der Text, den Sie in den Feldern
   25 und 26 eingetragen haben, gedruckt.           
                                                    
                                                    

   Hilfe f§r: ¯Platzhalter 1®
   --------------------------

   Geben Sie hier den Inhalt f§r die Platz-
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.22
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   halter {1} und {2} ein.                 
                                           
   Diese Platzhalter k¦nnen Sie bei der    
   Textbausteinanlage angeben.             
                                           
   Es stehen Ihnen jeweils 20 Stellen,     
   die Sie alpha-numerisch angeben k¦nnen, 
   f§r Ihre Eingabe zur Verf§gung.         
                                           
                                           

   Hilfe f§r: ¯Platzhalter 2®
   --------------------------

   Geben Sie hier den Inhalt f§r die Platz-
   halter {1} und {2} ein.                 
                                           
   Diese Platzhalter k¦nnen Sie bei der    
   Textbausteinanlage angeben.             
                                           
   Es stehen Ihnen jeweils 20 Stellen,     
   die Sie alpha-numerisch angeben k¦nnen, 
   f§r Ihre Eingabe zur Verf§gung.         
                                           
                                           
   ---------------------------------------------------


!R!FTMD13;FONT50080;SLS.122;EXIT;
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Men§fenster ¯Hauptmen§® / Auftrag... (AUF-001):Auftrag
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50080;SLS.122;EXIT;
   ÚÄÄÄÄÄÄÄÄÄÄÄÄ¿             
   ³ Auftrag... ³                ... Bearbeiten und drucken v. Auftr¥gen, Rechnungen u. Gutschriften.
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄ¿
   ³ Angebote/Rechnungen...  ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Auftragseingangsbuch    ³
   ³ Rechnungsausgangsbuch   ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Statistiklauf           ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
!R!FTMD13;FONT50055;SLS.142;EXIT;

!R!FTMD13;FONT50055;SLS.142;EXIT;
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.23
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;!R!FTMD13;FONT50055;SLS.142;EXIT;
   !R!FTMD13;FONT50055;SLS.142;EXIT;Ein-/Ausgabefelder f§r: Bearbeiten Sammelauftr¥ge (AUFM211)
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Ú(c) 1993 WINware ÄÄÄÄÄ WINware P.Mayer / A-1040 Wien ÄÄÄÄÄ Datum 01.12.93 (01)¿
   À!R!FTMD13;FONT50255;EXIT;ğğF-TastenğğOptionenğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğF1=Hilfeğğğğ!R!FTMD13;FONT50055;SLS.142;EXIT;Ù
   ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄBearbeiten Sammelauftr¥ge - 1/1Ä¿
   ³                                                                              ³
   ³  Sammelauftrag f§r:@@@@@@@@@@@@    ^^^^^^^                                   ³
   ³  Empf¥nger : D@@@@@@@@@@                   Vertreter       :@@@@@@@@@@@@@@   ³
   ³                                            Tour/Gebiet     :@@@@@@@@@@@@@@   ³
   ³  Name 1    :@@@@@@@@@@@@                   Preisgruppe     :@@@@@@@@@@@@@@   ³
   ³  Name 2    :@@@@@@@@@@@@                   Rabattgruppe    :@@@(0-8)         ³
   ³  Strasse   :@@@@@@@@@@@@                   Zahlungskond.   :@@@@@@@          ³
   ³  PLZ Ort   :@@@@@@@@@@@@                   USt.schl§ssel   :@@@@@@@          ³
   ³  Kurzbez.  :@@@@@@@@@@@@                   Rechnungskreis  :@@@(0-9)         ³
   ³                                            Rabattsatz      :@@@@@@@%         ³
   ³  Datum     :@@@@@@@@@@@@                   Provision       :@@@@@@@%         ³
   ³  Bearbeiter:@@@@@@@@@@@@                   W¥hrung         :@@@@@@@          ³
   ³  Versand   :@@@@@@@@@@@@                   Sprachcode      :@@@@@@@          ³
   ³  Rechnung  : D@@@@@@@@@@                                                     ³
   ³  Kst.stelle: T@@@@@@@@@@                                                     ³
   ³                                                                              ³
   ³  Kopftextbaustein :@@@@@@@@@@@@@@@@@@@@                                      ³
   ³  Fusstextbaustein :@@@@@@@@@@@@@@@@@@@@                                      ³
   ³  Platzhalter 1    :@@@@@@@@@@@@@@@@@@@@                                      ³
   ³                                                                              ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
   !R!FTMD13;FONT50255;EXIT;ğ[F1]=Hilfeğğ[Alt]+[F1]=Indexğğ[F2]=Suchenğğ[F10]=Men§ğğ[ESC]=EndeğğğğğğğğğğT02ğ!R!FTMD13;FONT50055;SLS.142;EXIT;



   Hilfe f§r: ¯Einzelauftr¥ge../Sammelaauftr¥ge...®
   ------------------------------------------------

   Ziel dieses Programms ist die  Verwaltung von Auftr¥gen und
   den zugeh¦rigen Vorg¥ngen, die seperat bearbeitet werden k¦nnen:
   
                   Lieferungen
                   R§cklieferungen
                   Rechnungen
                   Stornorechnungen
   
   Bei Einzelauftr¥gen zus¥tzlich:
   
                   Gutschriten
                   Direktrechnungen
                   Proformarechnungen
   
   Sammelrechnungen werden automatisch §ber die <Stapelabrechnung>
   erzeugt und k¦nnen wie alle Vorg¥nge bearbeitet werden.
   
   Jeder Vorgang basiert in der <Auftragsbearbeitung> auf einem
   Auftrag, der automatisch erzeugt wird, wenn z.B. eine Lieferung,
   Rechnung, etc. ohne vorherige Erfassung eines Auftrags bearbeitet
   wird.
   
   Bei Sammelauftr¥gen wird einmalig eine Sammelauftragsvereinbarung
   angelegt. Die Vorg¥nge zu Sammelauftr¥gen werden, nach dem Druck
   der Rechnungen im Rechnungsausgangsbuch, gel¦scht.
   
   
   Zus¥tzlich k¦nnen Sie festlegen, ob zu einem
   Auftrag bei <Einzelauftr¥gen>:
   
            Werkstattauftrag
            Packliste/Packzettel
            Fertigungszettel
   
   erstellt und §ber <Stapeldruck> gedruckt werden sollen.
   
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.24
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   Die Bestandsaktualisierung (Lagerabbuchung) erfolgt bei der Bear-
   beitung einer Lieferung (Lieferschein oder Direktrechnung).
   
   Die Bestandsaktualisierung erfolgt unmittelbar bei der Mengeneingabe
   innerhalb eines Liefervorgangs (Lieferschein, R§cklieferschein,
   Direktrechnung oder Stornorechnung).
   Dies gilt auch f§r die Artikelbestandteile einer St§ckliste sowie
   f§r Sreiennummern eines Artikels.
   Beim Verwerfen oder L¦schen eines Vorgangs werden die bereits er-
   folgten Bestandsver¥nderungeben r§ckg¥ngig gemacht.
   
   Die Berechnung der Lieferungen erfolgt entweder §ber die manuelle
   Berbeitung einer Rechnung (es werden alle gelieferten und noch nicht
   berechneten Positionen des Auftrags vorgeschlagen) oder §ber die
   Stapelabrechnung (f§r alle Lieferungen werden automatisch
   (Sammel)Rechnungen erstellt) .
   
   Bei der Direktrechnung erfolgt die Lieferung und Berechnung in
   einem Vorgang.
   
   Alle Vorg¥nge k¦nnen beliebig editiert werden, solange ein Auftrag
   nicht abgeschlossen ist.
   
   Ein Auftrag wird vom Programm abgeschlossen, wenn alle Positionen
   geliefert und berechnet wurden. Auftr¥ge und die zugeh¦rigen
   Vorg¥nge k¦nnen archiviert werden.
   Vorg¥nge k¦nnen sowohl §bernommen als auch sofort ausgedruckt
   werden.
   
   POSITIONSERFASSUNG
   
   Auswahlm¦glichkeiten §ber Funktionstasten
   
   F2  =  Suche nach Matchcode
   
   F3  =  Positionen einf§gen
   
   F4  =  Positionen l¦schen
   
   F5  =  Innerhalb bereits erfa¨ter Positionen eine Positionsart
          nach oben bewegen
   
   F6  =  Innerhalb bereits erfa¨ter Positionen eine Positionsart
          nach unten bewegen
   
   

   Hilfe f§r: ¯Sammelauftrag f§r®
   ------------------------------

   Geben Sie hier die Nummer des Kunden an.
   
   Folgende Auswahlm¦glichkeiten stehen Ihnen zur Verf§gung:
   
      F2        =  Suche nach Kurzbezeichnung
   
      SHIFT+F2  =  Auswahl
                   - Suche nach Bezeichnung
                   - Suche nach Nummer
                   - Suche nach Ansprechpartner
                   - Suche nach Postleitzahl
   
      F3        =  Suche nach Sammelauftragsvereinbarung
   
   Sie k¦nnen hier eine ¢nderung der Daten vornehmen, die jedoch nur
   f§r diese Vereinbahrung g§ltig sind und nicht die Kundenstammdaten
   ver¥ndern.
   
   

   Hilfe f§r: ¯Empf¥nger®
   ----------------------

   Geben Sie hier die Nummer des Kunden an. Das Programm stellt Ihnen 5
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.25
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   Stellen zur Verf§gung.                                              
                                                                       
   Folgende Auswahlm¦glichkeiten stehen Ihnen zur Verf§gung:           
                                                                       
      F2        =  Suche nach Kurzbezeichnung                          
                                                                       
      SHIFT+F2  =  Auswahl                                             
                   - Suche nach Bezeichnung                            
                   - Suche nach Nummer                                 
                   - Suche nach Ansprechpartner                        
                   - Suche nach Postleitzahl                           
                                                                       
      F10       =  neuer Kunde                                         
                                                                       
     - Falls die von Ihnen angegebene Kundennummer noch nicht im       
       Kundenstamm angelegt ist, erfolgt die Abfrage, ob der Kunde     
       angelegt werden soll, es wird automatisch in den <Kundenstamm>  
       zur Neuanlage verzweigt.                                        
                                                                       
     - Wenn Sie eine g§ltige Nummer eingeben (Kunde ist im Kundenstamm 
       vorhanden) springt das Programm in Feld 18.                     
                                                                       
       In die Felder 02 - 17 werden automatisch die Werte aus dem      
       Kundenstamm eingetragen.                                        
                                                                       
                                                                       
   

   Hilfe f§r: ¯Vertreter®
   ----------------------

   Hier wird der Vertreter gem¥¨ Ihrer Zuordnung im <Kundenstamm>
   vorgeschlagen.                                                      
                                                                       
   Sie k¦nnen eine ¢nderung vornehmen, die jedoch nur f§r diesen       
   Vorgang g§ltig ist und nicht im Kundenstamm ge¥ndert wird.          
                                                                       
   Der Vertreter mu¨ im <Vertreterstamm> angelegt sein.                
                                                                       
   F§r diesen Vertreter erfolgt die Provisionierung und die Abspeicher-
   ung der Statistik.                                                  
                                                                       
   In Feld 22 dieser Bildschirmmaske, wird die Kostenstelle, die Sie im
   <Vertreterstamm> zugeordnet haben, §bernommen.                      
                                                                       
   F2  =  Suche nach Vertreternummer.                                  
                                                                       
   Wird "999" f§r "Sammelvertreter" eingetragen, erfolgt die Ab-       
   speicherung der Statistik gem¥¨ Ihrer Festlegung im Programm        
   <Bearbeiten Mandant> Feld 08 (Seite 2/5).                           
                                                                       
   Die Vertreternummer dient zus¥tzlich als Selektionskriterium f§r    
   die Auswertung "Offene Auftr¥ge nach Kunde".                        
                                                                       
                                                                       
   

   Hilfe f§r: ¯Tour/Gebiet®
   ------------------------

   Dieses Feld enth¥lt die Nummer einer Tour oder eines Gebietes, die/
   das Sie dem Kunden zugeordnet haben.                                
                                                                       
   - Sie k¦nnen jedoch ¢nderungen vornehmen, die allerdings nur f§r    
     diesen Vorgang gelten und nicht im Kundenstamm gespeichert werden.
                                                                       
                                                                       
   

   Hilfe f§r: ¯Name 1®
   -------------------

   Dieses Feld enth¥lt den Namen des Kunden.
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.26
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;                                                                   
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   
   

   Hilfe f§r: ¯Preisgruppe®
   ------------------------

   Dieses Feld enth¥lt die Zuordnung f§r die Preisgruppe (Feld 15
   Kundenstamm). Die Preisgruppe bestimmt den Verkaufspreis (aus dem
   Artikel stamm) der dem Kunden in Rechnung gestellt werden soll.  
                                                                    
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen 
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.    
                                                                    
     F2  =  Auswahl aus den m¦glichen Preisgruppen                  
                                                                    
                                                                    
   

   Hilfe f§r: ¯Name 2®
   -------------------

   Dieses Feld enth¥lt einen Zusatz zum Kundennamen.
                                                                   
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   
   

   Hilfe f§r: ¯Rabattgruppe®
   -------------------------

   Dieses Feld enth¥lt die Nummer f§r eine Rabattgruppe.
                                                                       
   Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen      
   Vorgang gelten und nicht im Kundenstamm gespeichert werden.         
                                                                       
   Durch Zuordnung einer Nummer bestimmen Sie, ob dem Kunden ein Rabatt
   satz aus der Kunden/Artikelgruppen-Rabattmatrix (in Verbindung      
   mit Ihrem Eintrag im Artikelstamm Feld 30 - Rabattgruppe) zugeordnet
   werden soll.                                                        
                                                                       
   Sie haben die M¦glichkeit bis zu 8 Rabattgruppen in Verbindung mit  
   der Preisgruppe (Feld 17 Kundenstamm) zu 8 verschiedenen Artikel-   
   rabattgruppen anzulegen.                                            
   Ihr Eintrag von "0" bedeutet hier, da¨ dieser Kunde keinen Kunden/  
   Artikelgruppenrabatt bekommt.                                       
                                                                       
   Der Artikel mu¨ im Artikelstamm (Feld 33) als rabattierf¥hig ausge- 
   wiesen werden.                                                      
                                                                       
   Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen Vor- 
   gang gelten und nicht im Kundenstamm gespeichert werden.            
                                                                       
                                                                       
   

   Hilfe f§r: ¯Stra¨e®
   -------------------

   Diese Felder enthalten die vollst¥ndige Adresse des Kunden.
                                                                   
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   
   
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.27
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;
   Hilfe f§r: ¯Zahlungskonditionen®
   --------------------------------

   Dieses Feld enth¥lt einen Zahlencode f§r die Zahlungskonditionen des
   Kunden.                                                             
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
     Dr§cken Sie die F2-Taste. Es ¦ffnet sich ein Fenster mit drei Ein-
     gabefeldern:                                                      
                                                                       
     - ??? Tage Skonto                                                 
     - mit ?,? Prozent                                                 
     - ??? Tage ohne Skonto.                                           
                                                                       
     1. Tragen Sie dort zun¥chst die Zahl der Tage ein, die der Kunde  
        Skonto erhalten soll. Das Programm stellt daf§r 3 Stellen      
        numerisch zur Verf§gung.                                       
                                                                       
     2. Tragen Sie den Skonto-Prozentsatz ein. Das Programm stellt eine
        Vor- und eine Nachkommastelle zur Verf§gung.                   
                                                                       
     3. Setzen Sie im letzten Feld das Zahlungsziel "rein netto ohne   
        Abzug" ein (Anzahl Tage). Das Programm stellt maximal 3 Stellen
        numerisch zur Verf§gung.                                       
                                                                       
     Sie k¦nnen die Verschl§sselung der Zahlungskonditionen auch direkt
     im Feld eingeben.                                                 
                                                                       
     !!! WICHTIG !!!  In diesem Fall m§ssen Sie auch die f§hrenden     
                      Nullen mit eingeben.                             
                                                                       
     Verschl§sselung: 008 25 030                                       
                       ³  ³   ÀÄÄÄÄ  30 Tage ohne Skonto               
                       ³  ³                                            
                       ³  ÀÄÄÄÄÄÄÄÄ  2,5 % Skonto                      
                       ³                                               
                       ÀÄÄÄÄÄÄÄÄÄÄÄ  8 Tage Skonto                     
                                                                       
                                                                       
   

   Hilfe f§r: ¯PLZ/Ort®
   --------------------

   Diese Felder enthalten die vollst¥ndige Adresse des Kunden.
                                                                   
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   
                                                                   
   

   Hilfe f§r: ¯Umsatzsteuerschl§ssel®
   ----------------------------------

   Dieses Feld enth¥lt einen Schl§ssel f§r die Umsatzsteuerberechnung.
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
     0  =  keine Umsatzsteuer                                          
           (= keine Berechnung der Umsatzsteuer, i.d.R. bei Auslands-  
           kunden)                                                     
                                                                       
        !!! WICHTIG !!!  Sie k¦nnen einem Kunden kein Fremdw¥hrungs-   
                         kennzeichen zuweisen, solange der Umsatz- bzw.
                         Vorsteuerschl§ssel nicht auf "0" gesetzt ist! 
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.28
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;                                                                       
     1  =  mit Umsatzsteuer                                            
           (= gesonderte Berechnung der Umsatzsteuer zus¥tzlich zu den 
           jeweiligen Artikelpreisen)                                  
                                                                       
     2  =  Bruttopreise                                                
           (= Umsatzsteuer ist bereits im Artikelpreis enthalten)      
                                                                       
           !!! WICHTIG !!!  Reservieren Sie in diesem Fall eine eigene 
                            Preisgruppe, da dieser Preis dann ja ein   
                            Bruttopreis (incl. Umsatzsteuer) im        
                            Gegensatz zu den Nettoverkaufspreisen      
                            (excl. Umsatzsteuer) ist.                  
                                                                       
     F2  =  Auswahl aus den m¦glichen Eingaben.                        
                                                                       
                                                                       
   

   Hilfe f§r: ¯Kurzbezeichnung®
   ----------------------------

   - Falls dieser Kunde bereits im Kundenstamm angelegt ist, dient
     dieses Feld zu Ihrer Information.                             
     Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.   
                                                                   
                                                                   
   

   Hilfe f§r: ¯Rechnungskreis®
   ---------------------------

   Dieses Feld enth¥lt den Rechnungskreis, den Sie im <Kundenstamm>
   festgelegt haben.                                                   
                                                                       
   -Sie k¦nnen ¢nderungen vornehmen, die nur f§r diesen Vorgang        
    gelten und nicht im Kundenstamm gespeichert werden.                
                                                                       
    Die Eingabe oder Auswahl (mit der F2-Taste) des Rechnungskreises   
    1 - 9 legt die entsprechenden Abrechnungsperioden fest. Bei Eingabe
    eines Kennzeichens erfolgt sp¥ter eine Auswahlm¦glichkeit bei der  
    <Stapelabrechnung> in den Feldern "Abrechnungskreis" von/bis".     
                                                                       
    Sie k¦nnen die Vergabe eines Sammelrechnungskennzeichens z.B. nach 
    zeitlichen Kriterien vornehmen.                                    
                                                                       
    Beispiel: 1 = w¦chentliche Berechnung                              
              2 = zweiw¦chentliche Berechnung                          
              3 = monatliche Berechnung                                
              usw.                                                     
                                                                       
                                                                       
   

   Hilfe f§r: ¯Rabatsatz®
   ----------------------

   Dieses Feld enth¥lt den prozentualen Rabattsatz des Kunden.
                                                                     
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen  
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.     
                                                                     
   Der hier eingetragene Rabatt wird von dem Gesamtrechnungsbetrag in
   Abzug gebracht.                                                   
                                                                     
                                                                     
   

   Hilfe f§r: ¯Datum®
   ------------------

   Geben Sie hier das Datum ein,
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.29
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   an dem der Vorgang erfasst wurde.      
                                          
   Bitte geben Sie das Datum in der Form  
   TTMMJJ ein.                            
                                          
   Beispiel: Die Eingabe "120492" bedeutet
             12. April 1992.              
                                          
   Vorgeschlagen wird das aktuelle System-
   datum.                                 
                                          
                                          
   

   Hilfe f§r: ¯Provision®
   ----------------------

   Dieses Feld enth¥lt den prozentualen Provisionsanteil des
   Vertreters.                                                         
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
   - Wird hier eine Eingabe gemacht, so finden Ihre Angaben zum Pro-   
     visionssatz der einzelnen Artikel (Feld 06 Artikelstamm), sowie   
     beim jeweiligen Vertreter (Feld 02 Vertreterstamm) beim Gesamt-   
     rechnungsbetrag keine Ber§cksichtigung.                           
                                                                       
   - Bei Eingabe des Provisionsatzes 0.00" wird der im Artikel hinter- 
     legte Provisionssatz als Berechnungsgrundlage genommen, unabh¥ngig
     von dem im Vertreterstamm eingetragenen Provisionssatz.           
                                                                       
     Tragen Sie die Provision f§r diesen Vertreter in Prozenten ein.   
     Das Programm stellt 2 Vor- und 2 Nachkommastellen zur Verf§gung.  
                                                                       
                                                                       
   

   Hilfe f§r: ¯Bearbeiter®
   -----------------------

   Geben Sie hier den Mitarbeiter ein,
   der den Vorgang bearbeitet.         
                                       
     F2  =  Suche nach Mitarbeiter.    
                                       
   Nach dem <Statistiklauf> werden im  
   <Mitarbeiterstamm> die dem jeweili- 
   gen Mitarbeiter zugeordneten Ums¥tze
   aktualisiert.                       
                                       
                                       
   

   Hilfe f§r: ¯Versand®
   --------------------

   In diesem Feld k¦nnen Sie die Versandart angeben.
                                                     
     F2  =  Auswahl aus den angelegten Versandarten  
                                                     
   Umfang und Inhalt dieser Auswahlliste richtet sich
   nach Ihren eigenen Einstellungen beim Anlegen m¦g-
   licher Versandarten. Dies k¦nnen Sie in der Auf-  
   tragsbearbeitung in den Grundlagen im Men§punkt   
   <Versandarten> tun.                               
                                                     
                                                     
   

   Hilfe f§r: ¯Sprachcode®
   -----------------------

   Dieses Feld enth¥lt die Sprache, in der der Schriftverkehr mit dem
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.30
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   Kunden erfolgen soll.                                               
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
       F2  =  Auswahl aus den m¦glichen Fremdsprachen                  
                                                                       
     Die Auswahlwerte dieses Fensters richten sich nach Ihren Eingaben 
     in der "Finanzbuchhaltung" oder in der "Auftragsbearbeitung" in   
     den Grundlagen im Programm <Fremdw¥hrung/sprache>.                
                                                                       
   Beachten Sie bitte, da¨ bei Nutzung der Option "Fremdsprache" auch  
   ein entsprechendes Formular f§r die gew¥hlte Sprache existieren mu¨.
                                                                       
                                                                       
   

   Hilfe f§r: ¯Rechnung®
   ---------------------

   In diesem Feld k¦nnen Sie einen abweichenden Rechnungsempf¥nger
   bestimmen.
   
   Haben Sie im Kundenstamm bereits eine Festlegung getroffen, wird    
   hier die Kundennummer des abweichenden Rechnungsempf¥ngers ange-    
   zeigt.                                                              
                                                                       
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen    
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.       
                                                                       
   Bei der Bearbeitung einer Rechnung f§r einen Kunden mit abweichendem
   Rechnungsempf¥nger werden die Angaben des Kunden, an den die Rech-  
   nungsstellung erfolgen soll, im Anschriftenteil angezeigt.          
                                                                       
                                                                       
   

   Hilfe f§r: ¯Kostenstelle®
   -------------------------

   Die Kostenstelle wird automatisch vorgeschlagen, wenn Sie bei dem
   Vertreter im <Vertreterstamm> eine Zuordnung vorgenommen haben.  
                                                                    
   - Sie k¦nnen ¢nderungen vornehmen, die allerdings nur f§r diesen 
     Vorgang gelten und nicht im Kundenstamm gespeichert werden.    
                                                                    
     F2  =  Auswahl aus den bestehenden Kostenstellen.              
                                                                    
   Bei ¤bergabe in die Finanzbuchhaltung, werden die Erl¦se der     
   Fakturierung auf diese Kostenstelle verbucht.                    
                                                                    
   Neue Kostenstellen k¦nnen Sie in der "Finanzbuchhaltung" im      
   Programm <Kostenstellenstamm> erfassen.                          
                                                                    
                                                                    
   

   Hilfe f§r: ¯Kopftextbaustein®
   -----------------------------

   Hier haben Sie die M¦glichkeit einen Kopf-
   textbaustein f§r diesen Vorgang anzugeben.       
                                                    
      F2 =  Suche nach Textbausteinen               
                                                    
   Dieser Textbaustein wird beim Ausdruck im        
   Kopfteil der Formulare gedruckt.                 
                                                    
   Beachten Sie, da¨ Sie Platzhalter <{1} und {2}>  
   in Ihre Textbausteine einsetzen k¦nnen. In diese 
   Platzhalter wird der Text, den Sie in den Feldern
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.31
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   25 und 26 eingetragen haben, gedruckt.           
                                                    
                                                    
   

   Hilfe f§r: ¯Werkstattauftrag®
   -----------------------------

   Geben Sie hier an, ob ein Werkstattauftrag gedruckt werden soll.
   
   Werkstattauftr¥ge k¦nnen nur §ber das Programm <Stapeldruck Werk-
   stattauftr¥ge> gedruckt werden.
   
   Folgende Kennzeichen sind m¦glich:
   
     0 (nein)        = es soll kein Werkstattauftrag gedruckt werden
   
     1 (ja)          = es soll ein Werkstattauftrag gedruckt werden
   
     2 (ja)          = es wurde bereits ein Werkstattauftrag gedruckt
     (Druck erfolgt)   Dieses Kennzeichen wird vom Programm automatisch
                       gesetzt, wenn das Kennzeichen auf "1" gesetzt
                       war und §ber den Stapeldruck der Werkstatt-
                       auftrag gedruckt wurde.
   
     F2 = Auswahl aus den m¦glichen Kennzeichen.
   
   

   Hilfe f§r: ¯Fu¨textbaustein®
   ----------------------------

   Hier haben Sie die M¦glichkeit einen Fu¨-
   textbaustein f§r diesen Vorgang anzugeben.       
                                                    
      F2 =  Suche nach Textbausteinen               
                                                    
   Dieser Textbaustein wird beim Ausdruck im        
   Fu¨teil der Formulare gedruckt.                  
                                                    
   Beachten Sie, da¨ Sie Platzhalter <{1} und {2}>  
   in Ihre Textbausteine einsetzen k¦nnen. In diese 
   Platzhalter wird der Text, den Sie in den Feldern
   25 und 26 eingetragen haben, gedruckt.           
                                                    
                                                    
   

   Hilfe f§r: ¯Packliste/Packzettel®
   ---------------------------------

   Geben Sie hier an, ob eine Packliste und/oder Packzettel gedruckt
   werden soll.
   
   Diese k¦nnen nur §ber das Programm <Stapeldruck Packzettel> gedruckt
   werden.
   
   Folgende Kennzeichen sind m¦glich:
   
     0 (nein)    = es soll keine Packliste/Packzettel gedruckt werden
   
     1 (ja)      = es soll Packliste/Packzettel gedruckt werden
   
     2 (ja)     = es wurde bereits eine Packliste/Packzettel gedruckt
    (Druck erfolgt)  Dieses Kennzeichen wird vom Programm automatisch
                     gesetzt, wenn das Kennzeichen auf "1" gesetzt war
                     und §ber den Stapeldruck der Packzettel gedruckt
                     wurde.
   
        F2 = Auswahl aus den m¦glichen Kennzeichen.
   
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.32
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   
   ---------------------------------------------------


!R!FTMD13;FONT50080;SLS.122;EXIT;
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Men§fenster ¯Hauptmen§® / Auftrag... (AUF-001):Auftrag
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50080;SLS.122;EXIT;
   ÚÄÄÄÄÄÄÄÄÄÄÄÄ¿             
   ³ Auftrag... ³                ... Bearbeiten und drucken v. Auftr¥gen, Rechnungen u. Gutschriften.
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄ¿
   ³ Angebote/Rechnungen...  ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Auftragseingangsbuch    ³
   ³ Rechnungsausgangsbuch   ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Statistiklauf           ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
!R!FTMD13;FONT50055;SLS.142;EXIT;

!R!FTMD13;FONT50055;SLS.142;EXIT;
   !R!FTMD13;FONT50055;SLS.142;EXIT;Ein-/Ausgabefelder f§r: Bearbeiten Stapelabrechnug (AUFM212)
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Ú(c) 1993 WINware ÄÄÄÄÄ WINware P.Mayer / A-1040 Wien ÄÄÄÄÄ Datum 01.12.93 (01)¿
   À!R!FTMD13;FONT50255;EXIT;ğğF-TastenğğOptionenğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğF1=Hilfeğğğğ!R!FTMD13;FONT50055;SLS.142;EXIT;Ù
   ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄBearbeiten Stapelabrechnug - 1/1Ä¿
   ³                                                                              ³
   ³         Auftragsart          :@@@@@@@@@@@@@@                                 ³
   ³                                                                              ³
   ³         Abrechnungskreis 0   :@@@@@@@@@@@@@@                                 ³
   ³         Abrechnungskreis 1   :@@@@@@@@@@@@@@                                 ³
   ³         Abrechnungskreis 2   :@@@@@@@@@@@@@@                                 ³
   ³         Abrechnungskreis 3   :@@@@@@@@@@@@@@                                 ³
   ³         Abrechnungskreis 4   :@@@@@@@@@@@@@@                                 ³
   ³         Abrechnungskreis 5   :@@@@@@@@@@@@@@                                 ³
   ³         Abrechnungskreis 6   :@@@@@@@@@@@@@@                                 ³
   ³         Abrechnungskreis 7   :@@@@@@@@@@@@@@                                 ³
   ³         Abrechnungskreis 8   :@@@@@@@@@@@@@@                                 ³
   ³         Abrechnungskreis 9   :@@@@@@@@@@@@@@                                 ³
   ³                                                                              ³
   ³         Mindestbetrag netto  :@@@@@@@@@@@@@@                                 ³
   ³         Kopftextbaustein     :@@@@@@@@@@@@@@                                 ³
   ³         Fusstextbaustein     :@@@@@@@@@@@@@@                                 ³
   ³         Platzhalter 1        :@@@@@@@@@@@@@@                                 ³
   ³                                                                              ³
   ³                                                                              ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
   !R!FTMD13;FONT50255;EXIT;ğ[F1]=Hilfeğğ[Alt]+[F1]=Indexğğ[F2]=Suchenğğ[F10]=Men§ğğ[ESC]=EndeğğğğğğğğğğT02ğ!R!FTMD13;FONT50055;SLS.142;EXIT;



   Hilfe f§r: ¯Sammelrechnungslauf®
   --------------------------------

   Mit diesem Programm k¦nnen Sie Sammelrechnungen generieren.
   
   Es wird hier auf das im Kundenstamm eingegebene "Sammelrechnungs-
   Kennzeichen" zugegriffen.
   
   Sie k¦nnen dort die Vergabe eines Sammelrechnungskennzeichens z.B.
   nach zeitlichen Kriterien vornehmen.
   
   Beispiel: 1 = w¦chentliche Sammelrechnung
             2 = 2-w¦chentliche Sammelrechnunng
             3 = monatliche Sammelrechnung
                 usw...
   
   Alle Lieferscheine eines Auftrags zu einem Kunden, der im Kunden-
   stamm das "Sammelrechnungskennzeichen" auf 1 - 9 (f§r den Ab-
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.33
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   rechnungskreis) stehen hat, werden hier zusammengefasst und es wird
   e i n e Rechnung erstellt.
   
   Diese Sammelrechnung k¦nnen Sie im Programm <Stapeldruck Rechnungen>
   wie eine normale Rechnung ausdrucken lassen.
   
   Nach Angabe des Abrechnungskreises f§r den Sie die Generierung durch-
   f§hren m¦chten und des Mindestbetrages k¦nnen Sie einen Textvorspann
   eingeben, der zu Beginn der Sammelrechnungen erscheint.
   
   Dieser Textvorspann kann bis zu 50 Zeilen lang sein.
   
   

   Hilfe f§r: ¯Auftragsart®
   ------------------------

   Auswahlm¦glichkeiten
   
   F2  =  Einzelauftr¥ge
       =  Sammelauftr¥ge
       =  Einzel- und Sammelauftr¥ge
   
   

   Hilfe f§r: ¯Abrechnungskreis®
   -----------------------------

   Geben Sie hier den Abrechnungskreis an, f§r
   den Sie Sammelrechnungen generieren m¦chten.
   
   Im <Kundenstamm> haben Sie f§r jeden Kunden ein
   Sammelrechnungskennzeichen angelegt. Durch die-
   ses Kennzeichen haben Sie Ihre Kunden in ver-
   schiedene Abrechnungskreise eingeteilt.
   
   In der Kopferfassung haben Sie nochmals die
   M¦glichkeit dieses Sammelrechnungskennzeichen
   f§r diesen Auftrag,... zu ¥ndern.
   
   

   Hilfe f§r: ¯Abrechnungskreis®
   -----------------------------

   Geben Sie hier den Abrechnungskreis an, f§r
   den Sie Sammelrechnungen generieren m¦chten.
   
   Im <Kundenstamm> haben Sie f§r jeden Kunden ein
   Sammelrechnungskennzeichen angelegt. Durch die-
   ses Kennzeichen haben Sie Ihre Kunden in ver-
   schiedene Abrechnungskreise eingeteilt.
   
   In der Kopferfassung haben Sie nochmals die
   M¦glichkeit dieses Sammelrechnungskennzeichen
   f§r diesen Auftrag,... zu ¥ndern.
   
   

   Hilfe f§r: ¯Abrechnungskreis®
   -----------------------------

   Geben Sie hier den Abrechnungskreis an, f§r
   den Sie Sammelrechnungen generieren m¦chten.
   
   Im <Kundenstamm> haben Sie f§r jeden Kunden ein
   Sammelrechnungskennzeichen angelegt. Durch die-
   ses Kennzeichen haben Sie Ihre Kunden in ver-
   schiedene Abrechnungskreise eingeteilt.
   
   In der Kopferfassung haben Sie nochmals die
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.34
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   M¦glichkeit dieses Sammelrechnungskennzeichen
   f§r diesen Auftrag,... zu ¥ndern.
   
   

   Hilfe f§r: ¯Abrechnungskreis®
   -----------------------------

   Geben Sie hier den Abrechnungskreis an, f§r
   den Sie Sammelrechnungen generieren m¦chten.
   
   Im <Kundenstamm> haben Sie f§r jeden Kunden ein
   Sammelrechnungskennzeichen angelegt. Durch die-
   ses Kennzeichen haben Sie Ihre Kunden in ver-
   schiedene Abrechnungskreise eingeteilt.
   
   In der Kopferfassung haben Sie nochmals die
   M¦glichkeit dieses Sammelrechnungskennzeichen
   f§r diesen Auftrag,... zu ¥ndern.
   
   

   Hilfe f§r: ¯Abrechnungskreis®
   -----------------------------

   Geben Sie hier den Abrechnungskreis an, f§r
   den Sie Sammelrechnungen generieren m¦chten.
   
   Im <Kundenstamm> haben Sie f§r jeden Kunden ein
   Sammelrechnungskennzeichen angelegt. Durch die-
   ses Kennzeichen haben Sie Ihre Kunden in ver-
   schiedene Abrechnungskreise eingeteilt.
   
   In der Kopferfassung haben Sie nochmals die
   M¦glichkeit dieses Sammelrechnungskennzeichen
   f§r diesen Auftrag,... zu ¥ndern.
   
   

   Hilfe f§r: ¯Abrechnungskreis®
   -----------------------------

   Geben Sie hier den Abrechnungskreis an, f§r
   den Sie Sammelrechnungen generieren m¦chten.
   
   Im <Kundenstamm> haben Sie f§r jeden Kunden ein
   Sammelrechnungskennzeichen angelegt. Durch die-
   ses Kennzeichen haben Sie Ihre Kunden in ver-
   schiedene Abrechnungskreise eingeteilt.
   
   In der Kopferfassung haben Sie nochmals die
   M¦glichkeit dieses Sammelrechnungskennzeichen
   f§r diesen Auftrag,... zu ¥ndern.
   
   

   Hilfe f§r: ¯Abrechnungskreis®
   -----------------------------

   Geben Sie hier den Abrechnungskreis an, f§r
   den Sie Sammelrechnungen generieren m¦chten.
   
   Im <Kundenstamm> haben Sie f§r jeden Kunden ein
   Sammelrechnungskennzeichen angelegt. Durch die-
   ses Kennzeichen haben Sie Ihre Kunden in ver-
   schiedene Abrechnungskreise eingeteilt.
   
   In der Kopferfassung haben Sie nochmals die
   M¦glichkeit dieses Sammelrechnungskennzeichen
   f§r diesen Auftrag,... zu ¥ndern.
   
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.35
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   

   Hilfe f§r: ¯Abrechnungskreis®
   -----------------------------

   Geben Sie hier den Abrechnungskreis an, f§r
   den Sie Sammelrechnungen generieren m¦chten.
   
   Im <Kundenstamm> haben Sie f§r jeden Kunden ein
   Sammelrechnungskennzeichen angelegt. Durch die-
   ses Kennzeichen haben Sie Ihre Kunden in ver-
   schiedene Abrechnungskreise eingeteilt.
   
   In der Kopferfassung haben Sie nochmals die
   M¦glichkeit dieses Sammelrechnungskennzeichen
   f§r diesen Auftrag,... zu ¥ndern.
   
   

   Hilfe f§r: ¯Abrechnungskreis®
   -----------------------------

   Geben Sie hier den Abrechnungskreis an, f§r
   den Sie Sammelrechnungen generieren m¦chten.
   
   Im <Kundenstamm> haben Sie f§r jeden Kunden ein
   Sammelrechnungskennzeichen angelegt. Durch die-
   ses Kennzeichen haben Sie Ihre Kunden in ver-
   schiedene Abrechnungskreise eingeteilt.
   
   In der Kopferfassung haben Sie nochmals die
   M¦glichkeit dieses Sammelrechnungskennzeichen
   f§r diesen Auftrag,... zu ¥ndern.
   
   

   Hilfe f§r: ¯Abrechnungskreis®
   -----------------------------

   Geben Sie hier den Abrechnungskreis an, f§r
   den Sie Sammelrechnungen generieren m¦chten.
   
   Im <Kundenstamm> haben Sie f§r jeden Kunden ein
   Sammelrechnungskennzeichen angelegt. Durch die-
   ses Kennzeichen haben Sie Ihre Kunden in ver-
   schiedene Abrechnungskreise eingeteilt.
   
   In der Kopferfassung haben Sie nochmals die
   M¦glichkeit dieses Sammelrechnungskennzeichen
   f§r diesen Auftrag,... zu ¥ndern.
   
   

   Hilfe f§r: ¯Mindestbetrag netto®
   --------------------------------

   Ihre Sammelrechnung mu¨ den hier eingetragenen
   Mindest-Netto-Betrag haben, um generiert zu werden.
   
   Wenn der Netto-Betrag der kumulierten Liefer-
   scheine f§r einen Kunden den hier angegebenen
   Mindestbetrag unterschreitet, wird f§r diesen
   Kunden keine Sammelrechnung generiert.
   
   

   Hilfe f§r: ¯Kopftextbaustein®
   -----------------------------

   Hier haben Sie die M¦glichkeit einen Kopf-
   textbaustein f§r diesen Vorgang anzugeben.
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.36
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   
      F2 =  Suche nach Textbausteinen
   
   Dieser Textbaustein wird beim Ausdruck im
   Kopfteil der Formulare gedruckt.
   
   Beachten Sie, da¨ Sie Platzhalter <{1} und {2}>
   in Ihre Textbausteine einsetzen k¦nnen. In diese
   Platzhalter wird der Text, den Sie in den Feldern
   25 und 26 eingetragen haben, gedruckt.
   
   

   Hilfe f§r: ¯Fu¨textbaustein®
   ----------------------------

   Hier haben Sie die M¦glichkeit einen Fu¨-
   textbaustein f§r diesen Vorgang anzugeben.
   
      F2 =  Suche nach Textbausteinen
   
   Dieser Textbaustein wird beim Ausdruck im
   Fu¨teil der Formulare gedruckt.
   
   Beachten Sie, da¨ Sie Platzhalter <{1} und {2}>
   in Ihre Textbausteine einsetzen k¦nnen. In diese
   Platzhalter wird der Text, den Sie in den Feldern
   25 und 26 eingetragen haben, gedruckt.
   
   

   Hilfe f§r: ¯Platzhalter 1/2®
   ----------------------------

   Geben Sie hier den Inhalt f§r die Platz-
   halter {1} und {2} ein.
   
   Diese Platzhalter k¦nnen Sie bei der
   Textbausteinanlage angeben.
   
   Es stehen Ihnen jeweils 20 Stellen,
   die Sie alpha-numerisch angeben k¦nnen,
   f§r Ihre Eingabe zur Verf§gung.
   
   

   Hilfe f§r: ¯Platzhalter 1/2®
   ----------------------------

   Geben Sie hier den Inhalt f§r die Platz-
   halter {1} und {2} ein.
   
   Diese Platzhalter k¦nnen Sie bei der
   Textbausteinanlage angeben.
   
   Es stehen Ihnen jeweils 20 Stellen,
   die Sie alpha-numerisch angeben k¦nnen,
   f§r Ihre Eingabe zur Verf§gung.
   
   
   ---------------------------------------------------


!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.37
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;!R!FTMD13;FONT50080;SLS.122;EXIT;
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Men§fenster ¯Hauptmen§® / Auftrag... (AUF-001):Auftrag
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50080;SLS.122;EXIT;
   ÚÄÄÄÄÄÄÄÄÄÄÄÄ¿             
   ³ Auftrag... ³                ... Bearbeiten und drucken v. Auftr¥gen, Rechnungen u. Gutschriften.
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄ¿
   ³ Angebote/Rechnungen...  ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Auftragseingangsbuch    ³
   ³ Rechnungsausgangsbuch   ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Statistiklauf           ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
!R!FTMD13;FONT50055;SLS.142;EXIT;

!R!FTMD13;FONT50055;SLS.142;EXIT;
   !R!FTMD13;FONT50055;SLS.142;EXIT;Ein-/Ausgabefelder f§r: Bearbeiten Mehrfachvorg¥nge (AUFM213)
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Ú(c) 1993 WINware ÄÄÄÄÄ WINware P.Mayer / A-1040 Wien ÄÄÄÄÄ Datum 01.12.93 (01)¿
   À!R!FTMD13;FONT50255;EXIT;ğğF-TastenğğOptionenğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğF1=Hilfeğğğğ!R!FTMD13;FONT50055;SLS.142;EXIT;Ù
   ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄBearbeiten Mehrfachvorg¥nge - 1/1Ä¿
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³     ¤bernahme als       :  @@@@@@@@@@@@@@@                                   ³
   ³     Vorgangsdatum       :  @@@@@@@@@@@@@@@                                   ³
   ³                                                                              ³
   ³     Wiederholungskennz. :  @@@@@@@@@@@@@@@@                                  ³
   ³     Wiederholungsart    :  @@@@@@@@@@@@@@@@@@@@@@@                           ³
   ³                                                                              ³
   ³     Mehrfachvorgang     :  von @@@@@@      bis @@@@@@                        ³
   ³     Kundennummer        :  von D@@@@@      bis D@@@@@                        ³
   ³     Kundengruppe        :  von @@@@@@      bis @@@@@@                        ³
   ³     Auswertungskennz.   :  von @@@@@@      bis @@@@@@                        ³
   ³     Vertreter           :  von @@@@@@      bis @@@@@@                        ³
   ³     Tour/Gebiet         :  von @@@@@@      bis @@@@@@                        ³
   ³     Postleitzahl        :  von @@@@@@      bis @@@@@@                        ³
   ³                                                                              ³
   ³     Textvorspann @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                     ³
   ³                                                                              ³
   ³                                                                              ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
   !R!FTMD13;FONT50255;EXIT;ğ[F1]=Hilfeğğ[Alt]+[F1]=Indexğğ[F2]=Suchenğğ[F10]=Men§ğğ[ESC]=EndeğğğğğğğğğğT02ğ!R!FTMD13;FONT50055;SLS.142;EXIT;



   Hilfe f§r: ¯¤bernahme als®
   --------------------------

   Geben Sie hier ein, als was der hier generierte Mehrfachvorgang
   §bernommen werden soll.
   
     F2  =  Zur Auswahl stehen:
            - Auftragsbest¥tigung
            - Lieferung
            - Rechnung
            - Direktrechnung.
   
   Die Vorg¥nge werden dann in das Programm <Auftr¥ge, Rechnungen,...>
   §bernommen und sind dort aufrufbar.
   
   

   Hilfe f§r: ¯Vorgangsdatum®
   --------------------------

   In diesem Feld geben Sie das Datum ein, welches die hier generierten
   Vorg¥nge tragen sollen.
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.38
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   
   Geben Sie das Datum in der Form TTMMJJ ein, also je 2 Stellen f§r
   den Tag, den Monat und das Jahr.
   
   Beispiel: "090492" bedeutet: 9. April 1992.
   
   Es wird automatisch das aktuelle Systemdatum vorgeschlagen.
   
   

   Hilfe f§r: ¯Wiederhohlungskennzeichen®
   --------------------------------------

   Hier k¦nnen Sie das im Programm <Angebotserfassung> im Feld 27 =
   "Wiederholungskennzeichen" eingetragene Kennzeichen ansprechen.
   
   Mit Hilfe dieses Kennzeichens lassen sich wiederholbare Angebote in
   Hinsicht auf ihre periodische ¤bernahme als Rechnungen unterscheiden:
   z.B. k¦nnte eine "1" w¦chentliche, eine "2" monatliche und eine "3"
   viertelj¥hrliche Rechnungsstellung bedeuten, wobei die tats¥chliche
   Bedeutung frei von Ihnen bestimmt werden kann.
   
   Dieses Kennzeichen kann Werte von 0 - 9 annehmen.
   
   

   Hilfe f§r: ¯Wiederhohlungsart®
   ------------------------------

   Geben Sie hier an, ob es sich um kundenbezogene oder neutrale
   Vorg¥nge handelt.
   
     F2  =  Auswahl
            - Kundenbezogene Vorg¥nge
              alle Mehrfachvorg¥nge mit dem angegebenen
              Wiederholungskennzeichen werden f§r die
              entsprechenden Kunden generiert.
              Eine Selektion erfolgt nicht, es wird
              direkt in den Textvorspann verzweigt.
   
            - Neutrale Vorg¥nge
              hier mu¨ angegeben werden welche Mehr-
              fachvorg¥nge f§r welchen Kunden generiert
              werden sollen.
   
   

   Hilfe f§r: ¯Mehrfachvorgang von/bis®
   ------------------------------------

   Grenzen Sie in diesen Feldern den Bereich der Mehrfachvorg¥nge ein,
   welche §bernommen werden sollen.
   
   Dazu geben Sie in dem Feld "Mehrfachvorg¥nge von" den Mehrfachvor-
   gang ein, der vom Programm als untere Bereichsgrenze erkannt werden
   soll.
   
   Im Feld "Mehrfachvorgang bis" geben Sie entsprechend den Mehrfach-
   vorgang ein, der die obere Bereichsgrenze festlegt.
   
      F2       =   Suche nach Mehrfachvorgang
   
   

   Hilfe f§r: ¯Mehrfachvorgang von/bis®
   ------------------------------------

   Grenzen Sie in diesen Feldern den Bereich der Mehrfachvorg¥nge ein,
   welche §bernommen werden sollen.
   
   Dazu geben Sie in dem Feld "Mehrfachvorg¥nge von" den Mehrfachvor-
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.39
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   gang ein, der vom Programm als untere Bereichsgrenze erkannt werden
   soll.
   
   Im Feld "Mehrfachvorgang bis" geben Sie entsprechend den Mehrfach-
   vorgang ein, der die obere Bereichsgrenze festlegt.
   
      F2       =   Suche nach Mehrfachvorgang
   
   

   Hilfe f§r: ¯Kundennummer von/bis®
   ---------------------------------

   Innerhalb der oben eingegrenzten Mehrfachvorg¥nge k¦nnen Sie die
   Auswahl der zu §bernehmenden Vorg¥nge weiter eingrenzen.
   
   Dazu geben Sie im Feld "Kundennummer von" die Kundennummer an, die
   vom Programm als untere Bereichsgrenze erkannt werden soll.
   
   Im Feld "Kundennummer bis" geben Sie entsprechend die Kundennummer
   ein, die die obere Bereichsgrenze festlegt.
   
      F2       = Suche nach Kurzbezeichnung
   
      SHIFT+F2 = Auswahl
                 ş Suche nach Bezeichnung
                 ş Suche nach Nummer
                 ş Suche nach Ansprechpartner
                 ş Suche nach Postleitzahl.
   
   

   Hilfe f§r: ¯Kundennummer von/bis®
   ---------------------------------

   Innerhalb der oben eingegrenzten Mehrfachvorg¥nge k¦nnen Sie die
   Auswahl der zu §bernehmenden Vorg¥nge weiter eingrenzen.
   
   Dazu geben Sie im Feld "Kundennummer von" die Kundennummer an, die
   vom Programm als untere Bereichsgrenze erkannt werden soll.
   
   Im Feld "Kundennummer bis" geben Sie entsprechend die Kundennummer
   ein, die die obere Bereichsgrenze festlegt.
   
      F2       = Suche nach Kurzbezeichnung
   
      SHIFT+F2 = Auswahl
                 ş Suche nach Bezeichnung
                 ş Suche nach Nummer
                 ş Suche nach Ansprechpartner
                 ş Suche nach Postleitzahl.
   
   

   Hilfe f§r: ¯Kundengruppe von/bis®
   ---------------------------------

   Innerhalb der oben eingegrenzten Mehrfachvorg¥nge k¦nnen Sie die
   Auswahl der zu §bernehmenden Vorg¥nge weiter eingrenzen.
   
   Dazu geben Sie im Feld "Kundengruppe von" die Kundengruppe an, die
   vom Programm als untere Bereichsgrenze erkannt werden soll.
   
   Im Feld "Kundengruppe bis" geben Sie entsprechend die Kundengruppe
   ein, die die obere Bereichsgrenze festlegt.
   
   Es stehen Ihnen hierf§r 4 Stellen alpha-numerisch zur Verf§gung.
   
   

   Hilfe f§r: ¯Kundengruppe von/bis®
   ---------------------------------

   Innerhalb der oben eingegrenzten Mehrfachvorg¥nge k¦nnen Sie die
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.40
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   Auswahl der zu §bernehmenden Vorg¥nge weiter eingrenzen.
   
   Dazu geben Sie im Feld "Kundengruppe von" die Kundengruppe an, die
   vom Programm als untere Bereichsgrenze erkannt werden soll.
   
   Im Feld "Kundengruppe bis" geben Sie entsprechend die Kundengruppe
   ein, die die obere Bereichsgrenze festlegt.
   
   Es stehen Ihnen hierf§r 4 Stellen alpha-numerisch zur Verf§gung.
   
   

   Hilfe f§r: ¯Auswertungskennzeichen®
   -----------------------------------

   Innerhalb der oben eingegrenzten Mehrfachvorg¥nge k¦nnen Sie die
   Auswahl der zu §bernehmenden Vorg¥nge weiter eingrenzen.
   
   Dazu geben Sie im Feld "Auswertungskennzeichen von" das Auswertungs-
   kennzeichen an, das vom Programm als untere Bereichsgrenze erkannt
   werden soll.
   
   Im Feld "Auswertungskennzeichen bis" geben Sie entsprechend das Aus-
   wertungskennzeichen ein, das die obere Bereichsgrenze festlegt.
   
   Es stehen Ihnen hierf§r 4 Stellen alpha-numerisch zur Verf§gung.
   
   

   Hilfe f§r: ¯Auswertungskennzeichen®
   -----------------------------------

   Innerhalb der oben eingegrenzten Mehrfachvorg¥nge k¦nnen Sie die
   Auswahl der zu §bernehmenden Vorg¥nge weiter eingrenzen.
   
   Dazu geben Sie im Feld "Auswertungskennzeichen von" das Auswertungs-
   kennzeichen an, das vom Programm als untere Bereichsgrenze erkannt
   werden soll.
   
   Im Feld "Auswertungskennzeichen bis" geben Sie entsprechend das Aus-
   wertungskennzeichen ein, das die obere Bereichsgrenze festlegt.
   
   Es stehen Ihnen hierf§r 4 Stellen alpha-numerisch zur Verf§gung.
   
   

   Hilfe f§r: ¯Vertreter von/bis®
   ------------------------------

   Innerhalb der oben eingegrenzten Mehrfachvorg¥nge k¦nnen Sie die
   Auswahl der zu §bernehmenden Vorg¥nge weiter eingrenzen.
   
   Dazu geben Sie im Feld "Vertreter von" den Vertreter an, der vom
   Programm als untere Bereichsgrenze erkannt werden soll.
   
   Im Feld "Vertreter bis" geben Sie entsprechend den Vertreter ein,
   der die obere Bereichsgrenze festlegt.
   
      F2       = Suche nach Vertreternummer.
   
   

   Hilfe f§r: ¯Vertreter von/bis®
   ------------------------------

   Innerhalb der oben eingegrenzten Mehrfachvorg¥nge k¦nnen Sie die
   Auswahl der zu §bernehmenden Vorg¥nge weiter eingrenzen.
   
   Dazu geben Sie im Feld "Vertreter von" den Vertreter an, der vom
   Programm als untere Bereichsgrenze erkannt werden soll.
   
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.41
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   Im Feld "Vertreter bis" geben Sie entsprechend den Vertreter ein,
   der die obere Bereichsgrenze festlegt.
   
      F2       = Suche nach Vertreternummer.
   
   

   Hilfe f§r: ¯Tour/Gebiet von/bis®
   --------------------------------

   Innerhalb der oben eingegrenzten Mehrfachvorg¥nge k¦nnen Sie die
   Auswahl der zu §bernehmenden Vorg¥nge weiter eingrenzen.
   
   Dazu geben Sie im Feld "Tour/Gebiet von" die/das Tour/Gebiet an,
   die/das vom Programm als untere Bereichsgrenze erkannt werden soll.
   
   Im Feld "Tour/Gebiet bis" geben Sie entsprechend die/das Tour/Gebiet
   ein, die/das die obere Bereichsgrenze festlegt.
   
   Sie k¦nnen hier die Werte 00 - 99 eingeben.
   
   

   Hilfe f§r: ¯Tour/Gebiet von/bis®
   --------------------------------

   Innerhalb der oben eingegrenzten Mehrfachvorg¥nge k¦nnen Sie die
   Auswahl der zu §bernehmenden Vorg¥nge weiter eingrenzen.
   
   Dazu geben Sie im Feld "Tour/Gebiet von" die/das Tour/Gebiet an,
   die/das vom Programm als untere Bereichsgrenze erkannt werden soll.
   
   Im Feld "Tour/Gebiet bis" geben Sie entsprechend die/das Tour/Gebiet
   ein, die/das die obere Bereichsgrenze festlegt.
   
   Sie k¦nnen hier die Werte 00 - 99 eingeben.
   
   

   Hilfe f§r: ¯Postleitzahl von/bis®
   ---------------------------------

   Innerhalb der oben eingegrenzten Mehrfachvorg¥nge k¦nnen Sie die
   Auswahl der zu §bernehmenden Vorg¥nge weiter eingrenzen.
   
   Dazu geben Sie im Feld "Postleitzahl von" die Postleitzahl an, die
   vom Programm als untere Bereichsgrenze erkannt werden soll.
   
   Im Feld "Postleitzahl bis" geben Sie entsprechend die Postleitzahl
   ein, die die obere Bereichsgrenze festlegt.
   
   Es stehen Ihnen hierf§r 10 Stellen alphanumerisch zur Verf§gung.
   
   

   Hilfe f§r: ¯Postleitzahl von/bis®
   ---------------------------------

   Innerhalb der oben eingegrenzten Mehrfachvorg¥nge k¦nnen Sie die
   Auswahl der zu §bernehmenden Vorg¥nge weiter eingrenzen.
   
   Dazu geben Sie im Feld "Postleitzahl von" die Postleitzahl an, die
   vom Programm als untere Bereichsgrenze erkannt werden soll.
   
   Im Feld "Postleitzahl bis" geben Sie entsprechend die Postleitzahl
   ein, die die obere Bereichsgrenze festlegt.
   
   Es stehen Ihnen hierf§r 10 Stellen alphanumerisch zur Verf§gung.
   
   

!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.42
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   Hilfe f§r: 
   -----------

   ---------------------------------------------------


!R!FTMD13;FONT50080;SLS.122;EXIT;
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Men§fenster ¯Hauptmen§® / Auftrag... (AUF-001):Auftrag
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50080;SLS.122;EXIT;
   ÚÄÄÄÄÄÄÄÄÄÄÄÄ¿             
   ³ Auftrag... ³                ... Bearbeiten und drucken v. Auftr¥gen, Rechnungen u. Gutschriften.
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄ¿
   ³ Angebote/Rechnungen...  ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Auftragseingangsbuch    ³
   ³ Rechnungsausgangsbuch   ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Statistiklauf           ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
!R!FTMD13;FONT50055;SLS.142;EXIT;

!R!FTMD13;FONT50055;SLS.142;EXIT;
   !R!FTMD13;FONT50055;SLS.142;EXIT;Ein-/Ausgabefelder f§r: Druck Auftragseingangsbuch (AUFM350)
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Ú(c) 1993 WINware ÄÄÄÄÄ WINware P.Mayer / A-1040 Wien ÄÄÄÄÄ Datum 01.12.93 (01)¿
   À!R!FTMD13;FONT50255;EXIT;ğğF-TastenğğOptionenğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğF1=Hilfeğğğğ!R!FTMD13;FONT50055;SLS.142;EXIT;Ù
   ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄDruck Auftragseingangsbuch - 1/1Ä¿
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³                AE-Buch detailiert  :  @@@@@@@@@@@@@@                         ³
   ³                AE-Buch §bersicht   :  @@@@@@@@@@@@@@                         ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
   !R!FTMD13;FONT50255;EXIT;ğ[F1]=Hilfeğğ[Alt]+[F1]=Indexğğ[F2]=Suchenğğ[F10]=Men§ğğ[ESC]=EndeğğğğğğğğğğT02ğ!R!FTMD13;FONT50055;SLS.142;EXIT;



   Hilfe f§r: ¯Auftragseingangsbuch®
   ---------------------------------

   Das Auftragseingangsbuch erm¦glicht Ihnen eine ¤bersicht §ber die
   eingegangenen Auftr¥ge.
   
   Sie k¦nnen ausw¥hlen, wie Sie das Auftragseingangsbuch ausdrucken
   m¦chten. Zur Auswahl stehen folgende Varianten:
   
   - detailiert
     In der detailierten Liste werden zu jedem Auftrag die einzelnen
     Positionen aufgef§hrt. Weiterhin erhalten Sie Informationen §ber
     Auftragsnummer/-datum, die Lieferwoche, die Auftragsmenge und den
     Auftragswert.
   
   - ¤bersicht
     In der Auftrags§bersicht erhalten Sie neben der Auftragsnummer
     und dem Datum Informationen §ber den Vertreter, den Bearbeiter
     und den Auftragswert.
   
   Nach dem Ausdruck erfolgt eine Abfrage, ob der Ausdruck in Ordnung
   war. Wenn Sie hier "J" eingeben, werden alle im Auftragseingangsbuch
   ausgewiesenen Auftr¥ge markiert und bei sp¥teren Ausdrucken nicht
   mehr mit gedruckt.
   
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.43
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   Beantworten Sie diese Abfrage mit "N", so werden die ausgedruckten
   Auftr¥ge bei einem sp¥teren Ausdruck wieder mit ausgegeben.
   
   !!! WICHTIG !!!   Vor dem Ausdruck sollten Sie §berpr§fen, ob der
                     richtige Drucker eingestellt ist. Sie k¦nnen dies
                     jederzeit mit SHIFT+F1 §berpr§fen und gegebenen-
                     falls ¥ndern.
   
   

   Hilfe f§r: ¯Auftragseingangsbuch detailiert®
   --------------------------------------------

   Geben Sie hier an, ob das Auftragseingangsbuch detailliert
   ausgegeben werden soll oder nicht.
   
   Detailliert bedeutet, da¨ jede Position einzeln aufgef§hrt wird.
   Sie k¦nnen hier ersehen:
   
     - das Auftragsdatum
     - den Kunden
     - die Artikel
     - die Lieferwoche
     - den Auftragswert.
   
   Um eine ¤bersicht §ber alle Auftr¥ge zu erhalten w¥hlen Sie bitte im
   n¥chsten Feld "AE-Buch ¤bersicht: ja".
   
   

   Hilfe f§r: ¯Auftragseingangsbuch §bersicht®
   -------------------------------------------

   Geben Sie hier an, ob das Auftragseingangsbuch als ¤bersicht
   ausgegeben werden soll oder nicht.
   
   In dieser ¤bersicht sind enthalten:
   
     - das Auftragsdatum
     - der Kunde
     - der Vertreter
     - der Bearbeiter
     - der Auftragswert.
   
   Um ein Auftragseingangsbuch mit den einzelnen Artikelpositionen zu
   erhalten w¥hlen Sie bitte im vorigen Feld "AE-Buch detailliert: ja".
   
   
   ---------------------------------------------------


!R!FTMD13;FONT50080;SLS.122;EXIT;
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Men§fenster ¯Hauptmen§® / Auftrag... (AUF-001):Auftrag
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50080;SLS.122;EXIT;
   ÚÄÄÄÄÄÄÄÄÄÄÄÄ¿             
   ³ Auftrag... ³                ... Bearbeiten und drucken v. Auftr¥gen, Rechnungen u. Gutschriften.
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄ¿
   ³ Angebote/Rechnungen...  ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Auftragseingangsbuch    ³
   ³ Rechnungsausgangsbuch   ³
   ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
   ³ Statistiklauf           ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
!R!FTMD13;FONT50055;SLS.142;EXIT;

!R!FTMD13;FONT50055;SLS.142;EXIT;
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.44
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;!R!FTMD13;FONT50055;SLS.142;EXIT;
   !R!FTMD13;FONT50055;SLS.142;EXIT;Ein-/Ausgabefelder f§r: Druck Rechnungsausgangsbuch (AUFM360)
   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
!R!FTMD13;FONT50055;SLS.142;EXIT;
   Ú(c) 1993 WINware ÄÄÄÄÄ WINware P.Mayer / A-1040 Wien ÄÄÄÄÄ Datum 01.12.93 (01)¿
   À!R!FTMD13;FONT50255;EXIT;ğğF-TastenğğOptionenğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğğF1=Hilfeğğğğ!R!FTMD13;FONT50055;SLS.142;EXIT;Ù
   ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄDruck Rechnungsausgangsbuch - 1/1Ä¿
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³                Bis Rechnungsdsatum  :  @@@@@@@@@@@@@@                        ³
   ³                Bis Rechnungsnummer  :  @@@@@@@@@@@@@@                        ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ³                                                                              ³
   ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
   !R!FTMD13;FONT50255;EXIT;ğ[F1]=Hilfeğğ[Alt]+[F1]=Indexğğ[F2]=Suchenğğ[F10]=Men§ğğ[ESC]=EndeğğğğğğğğğğT02ğ!R!FTMD13;FONT50055;SLS.142;EXIT;



   Hilfe f§r: ¯Rechnungsausgangsbuch®
   ----------------------------------

   Alle Erl¦se und Ums¥tze aus den bisher gedruckten Rechnungen,
   Gutschriften und Stornorechnungen werden hier ausgedruckt.
   
   Wenn Sie die an den Druck anschliessende OK-Abfrage mit "J"
   beantworten, wird vermerkt, welche Rechnungen, Gutschriften,... im
   RA-Buch ausgedruckt worden sind.
   
   Beim n¥chsten Ausdruck werden bereits gedruckte Formulare nicht mehr
   gedruckt.
   
   Falls Sie mit der Finanzbuchhaltung arbeiten werden die Rechnungen,
   Gutschriften,... anschliessend in die Finanzbuchhaltung §bernommen
   und dort automatisch verbucht.
   
   Anschliessend k¦nnen Sie den Statistiklauf starten. Diesen
   k¦nnen Sie aber auch separat zu einem sp¥teren Zeitpunkt star-
   ten, da die Verarbeitung der Daten l¥ngere Zeit in Anspruch
   nehmen kann.
   
   

   Hilfe f§r: ¯Bis Rechnungsdatum®
   -------------------------------

   Geben Sie hier das Rechnungsdatum ein bis zu dem die Rechnungen in
   das Rechnungseingangsbuch einflie¨en sollen.
   
   Die Rechnungen die vor bzw. an diesem Tag erstellt wurden, werden
   dann im Rechnungsausgangsbuch ausgewiesen.
   
   Geben Sie hier das Datum im Format TTMMJJ ein, d.h. es stehen Ihnen
   jeweils 2 Stellen f§r den Tag, den Monat und das Jahr zur Verf§gung.
   
   Beispiel: "100492" bedeutet 10. April 1992.
   
   Vom Programm wird hier automatisch das aktuelle Systemdatum vorge-
   schlagen.
   
   

   Hilfe f§r: ¯Bis Rechnungsnummer®
   --------------------------------

   Geben Sie hier die letzte Rechnungsnummer ein, die ins Rechnungsein-
   gangsbuch einflie¨en soll.
!R!FTMD13;FONT50055;SLPP99;SLS.142;SLM0.7;STM0.2;MAP0,.15;EXIT;WINware (C) 1988/1993                                  II. Bereich: Auftrag... / 1.45
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

!R!FTMD13;FONT50055;SLS.142;EXIT;   
   Wenn Sie dieses Feld mit RETURN §bergehen, wird die gr¦¨tm¦gliche
   Nummer "999999" vorgeschlagen. Es werden dann alle noch nicht ver-
   arbeiteten Rechnungen bis zu dem im letzten Feld genannten Datum aus-
   gegeben.
   
   
   ---------------------------------------------------

