@echo off
    dir *.arc
REM del *.arc
rem arc a syhlp syhlp10.043
rem arc a syhlp syindex.043
REM arc a sthlp sthlp10.043
REM arc a sthlp stindex.043
REM arc a fihlp fihlp10.043
REM arc a fihlp fiindex.043
REM arc a auhlp auhlp10.043
REM arc a auhlp auindex.043
REM arc a kahlp kahlp10.043
REM arc a kahlp kaindex.043
    arc l syhlp
    arc l sthlp
pause
    arc l fihlp
    arc l auhlp
pause
REM arc l kahlp

